--------------------------------------------------------
--  DDL OPERATIONS
--------------------------------------------------------

ALTER TABLE PETPE_TRADINGPARTNER ADD PEM_IDENTIFIER VARCHAR2(255);
ALTER TABLE PETPE_APPLICATION ADD PEM_IDENTIFIER VARCHAR2(255);
ALTER TABLE PETPE_PROCESSDOCS MODIFY DOCTYPE VARCHAR2(255);
