--------------------------------------------------------
--  DDL for Table PETPE_APPLICATION
--------------------------------------------------------
CREATE TABLE PETPE_APPLICATION
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    APPLICATION_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    APPLICATION_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    EMAIL_ID VARCHAR2(250 BYTE) NOT NULL ENABLE,
    PHONE VARCHAR2(15 BYTE) NOT NULL ENABLE,
    APP_INTEGRATION_PROTOCOL VARCHAR2(10 BYTE) NOT NULL ENABLE,
    APP_PICKUP_FILES VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    APP_DROP_FILES VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    APP_PROTOCOL_REF VARCHAR2(20 BYTE) NOT NULL ENABLE,
    APP_IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE ,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6), PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_APP_ACTIVITY_HISTORY
--------------------------------------------------------
CREATE TABLE PETPE_APP_ACTIVITY_HISTORY
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    APP_REF_ID VARCHAR2(30 BYTE),
    USER_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    USER_ID VARCHAR2(15 BYTE) NOT NULL ENABLE,
    ACTIVITY_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    ACTIVITY CLOB,  PRIMARY KEY (PK_ID)
    );

--------------------------------------------------------
--  DDL for Table PETPE_APPLICATION_SFG
--------------------------------------------------------
CREATE TABLE PETPE_APPLICATION_SFG
   (	PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
	APPLICATION_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
	APPLICATION_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
	EMAIL_ID VARCHAR2(250 BYTE) NOT NULL ENABLE,
	PHONE VARCHAR2(15 BYTE) NOT NULL ENABLE,
	APP_INTEGRATION_PROTOCOL VARCHAR2(50 BYTE) NOT NULL ENABLE,
	APP_PICKUP_FILES VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
	APP_DROP_FILES VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
	APP_PROTOCOL_REF VARCHAR2(20 BYTE) NOT NULL ENABLE,
	APP_IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
	CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
	LAST_UPDATED_BY VARCHAR2(15 BYTE),
	LAST_UPDATED_DT TIMESTAMP (6),
	 PRIMARY KEY (PK_ID)
	);

