--------------------------------------------------------
--  DDL for Table PETPE_PROCESS
--------------------------------------------------------
CREATE TABLE PETPE_PROCESS
   (    SEQ_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PARTNER_PROFILE VARCHAR2(20 BYTE) NOT NULL ENABLE,
    APPLICATION_PROFILE VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SEQ_TYPE VARCHAR2(50 BYTE) NOT NULL ENABLE,
    FLOW VARCHAR2(50 BYTE) NOT NULL ENABLE,
    FILE_NAME VARCHAR2(200 BYTE) , PRIMARY KEY (SEQ_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_PROCESSDOCS
--------------------------------------------------------
CREATE TABLE PETPE_PROCESSDOCS
   (    PK_ID VARCHAR2(254 BYTE) NOT NULL ENABLE,
    PROCESS_REF VARCHAR2(50 BYTE) NOT NULL ENABLE,
    DOCTYPE VARCHAR2(50 BYTE),
    PARTNERID VARCHAR2(50 BYTE),
    RECIVERID VARCHAR2(50 BYTE),
    DOCTRANS VARCHAR2(50 BYTE),
    FILENAME_PATTERN VARCHAR2(200 BYTE),
    PROCESS_RULESEQ VARCHAR2(200 BYTE),
    PROCESSRULE_REF VARCHAR2(254 BYTE) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_PROCESSRULES
--------------------------------------------------------
CREATE TABLE PETPE_PROCESSRULES
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    RULE_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    RULE_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PROPERTY_NAME_1 VARCHAR2(500 BYTE),
    PROPERTY_NAME_2 VARCHAR2(200 BYTE),
    PROPERTY_NAME_3 VARCHAR2(200 BYTE),
    PROPERTY_NAME_4 VARCHAR2(200 BYTE),
    PROPERTY_NAME_5 VARCHAR2(200 BYTE),
    PROPERTY_NAME_6 VARCHAR2(200 BYTE),
    PROPERTY_NAME_7 VARCHAR2(200 BYTE),
    PROPERTY_NAME_8 VARCHAR2(200 BYTE),
    PROPERTY_NAME_9 VARCHAR2(200 BYTE),
    PROPERTY_NAME_10 VARCHAR2(200 BYTE),
    PROPERTY_NAME_11 VARCHAR2(200 BYTE),
    PROPERTY_NAME_12 VARCHAR2(200 BYTE),
    PROPERTY_NAME_13 VARCHAR2(200 BYTE),
    PROPERTY_NAME_14 VARCHAR2(200 BYTE),
    PROPERTY_NAME_15 VARCHAR2(200 BYTE) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_RULES
--------------------------------------------------------
CREATE TABLE PETPE_RULES
   (    RULE_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    RULE_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    BUSINESS_PROCESS_ID VARCHAR2(120 BYTE) NOT NULL ENABLE,
    PROPERTY_NAME_1 VARCHAR2(200 BYTE),
    PROPERTY_NAME_2 VARCHAR2(200 BYTE),
    PROPERTY_NAME_3 VARCHAR2(200 BYTE),
    PROPERTY_NAME_4 VARCHAR2(200 BYTE),
    PROPERTY_NAME_5 VARCHAR2(200 BYTE),
    PROPERTY_NAME_6 VARCHAR2(200 BYTE),
    PROPERTY_NAME_7 VARCHAR2(200 BYTE),
    PROPERTY_NAME_8 VARCHAR2(200 BYTE),
    PROPERTY_NAME_9 VARCHAR2(200 BYTE),
    PROPERTY_NAME_10 VARCHAR2(200 BYTE),
    PROPERTY_NAME_11 VARCHAR2(200 BYTE),
    PROPERTY_NAME_12 VARCHAR2(200 BYTE),
    PROPERTY_NAME_13 VARCHAR2(200 BYTE),
    PROPERTY_NAME_14 VARCHAR2(200 BYTE),
    PROPERTY_NAME_15 VARCHAR2(200 BYTE) , PRIMARY KEY (RULE_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_B2B_ACTIVITY_HISTORY
-------------------------------------------------------
CREATE TABLE PETPE_B2B_ACTIVITY_HISTORY

   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PROCESS_REF_ID VARCHAR2(30 BYTE),
    USER_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    USER_ID VARCHAR2(15 BYTE) NOT NULL ENABLE,
    ACTIVITY_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    ACTIVITY CLOB, PRIMARY KEY (PK_ID)
   );
