--------------------------------------------------------
--  DDL STATEMENT
--------------------------------------------------------
ALTER TABLE PETPE_TRANSFERINFO DROP (FUNCTIONAL_ACK_DATE, FUNCTIONAL_ACK_TIME);

ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN ISA_CONTROL_NUMBER TO ISA_CTL;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN GS_CONTROL_NUMBER TO GS_CTL;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN ST_CONTROL_NUMBER TO ST_CTL;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN FUNCTIONAL_ACK_REQUEST TO FA_REQ;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN SEGMENT_COUNT TO SEG_CNT;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN IDOC_NUMBER TO APP_TRAN_NUM;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN SAP_FA TO APP_FA;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN CHAR_CNT TO SRC_CHAR_CNT;

ALTER TABLE PETPE_TRANSFERINFO
  ADD (FA_DTM TIMESTAMP(6),
    APP_FA_STUS VARCHAR2(15),
	APP_FA_DTM VARCHAR2(15),
	DST_CHAR_CNT VARCHAR2(20),
	DST_PROCL_CNT VARCHAR2(20),
	BU_DIVNAME VARCHAR2(20),
	TP_REF_ID VARCHAR2(50),
	DLE_DTM TIMESTAMP(6));

CREATE INDEX FA_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (FA_DTM);
CREATE INDEX DLE_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (DLE_DTM);
