--------------------------------------------------------
--  DDL for Table PETPE_POOLING_INTERVAL
--------------------------------------------------------
CREATE TABLE PETPE_POOLING_INTERVAL
(
    PK_ID           VARCHAR2(50 BYTE) NOT NULL ENABLE,
    INTERVAL        VARCHAR2(50 BYTE) NOT NULL ENABLE,
    SEQ             NUMBER NOT NULL ENABLE,
    DESCRIPTION     VARCHAR2(255 BYTE),
    CREATED_BY      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP(6),
    UNIQUE (SEQ),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_CORRELATION_NAMES
--------------------------------------------------------
CREATE TABLE PETPE_CORRELATION_NAMES
(
    PK_ID               VARCHAR2(20 BYTE) NOT NULL ENABLE,
    CORRELATION_NAME_1  VARCHAR2(200 BYTE),
    CORRELATION_NAME_2  VARCHAR2(200 BYTE),
    CORRELATION_NAME_3  VARCHAR2(200 BYTE),
    CORRELATION_NAME_4  VARCHAR2(200 BYTE),
    CORRELATION_NAME_5  VARCHAR2(200 BYTE),
    CORRELATION_NAME_6  VARCHAR2(200 BYTE),
    CORRELATION_NAME_7  VARCHAR2(200 BYTE),
    CORRELATION_NAME_8  VARCHAR2(200 BYTE),
    CORRELATION_NAME_9  VARCHAR2(200 BYTE),
    CORRELATION_NAME_10 VARCHAR2(200 BYTE),
    CORRELATION_NAME_11 VARCHAR2(200 BYTE),
    CORRELATION_NAME_12 VARCHAR2(200 BYTE),
    CORRELATION_NAME_13 VARCHAR2(200 BYTE),
    CORRELATION_NAME_14 VARCHAR2(200 BYTE),
    CORRELATION_NAME_15 VARCHAR2(200 BYTE),
    CORRELATION_NAME_16 VARCHAR2(200 BYTE),
    CORRELATION_NAME_17 VARCHAR2(200 BYTE),
    CORRELATION_NAME_18 VARCHAR2(200 BYTE),
    CORRELATION_NAME_19 VARCHAR2(200 BYTE),
    CORRELATION_NAME_20 VARCHAR2(200 BYTE),
    CORRELATION_NAME_21 VARCHAR2(200 BYTE),
    CORRELATION_NAME_22 VARCHAR2(200 BYTE),
    CORRELATION_NAME_23 VARCHAR2(200 BYTE),
    CORRELATION_NAME_24 VARCHAR2(200 BYTE),
    CORRELATION_NAME_25 VARCHAR2(200 BYTE),
    CREATED_BY          VARCHAR2(15 BYTE),
    LAST_UPDATED_BY     VARCHAR2(15 BYTE),
    LAST_UPDATED_DT     TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);
