-------------------------------------------------------------
--   ORACLE DDL STATEMENT FOR 	PETPE_GOOGLE_DRIVE
-------------------------------------------------------------

CREATE TABLE PETPE_GOOGLE_DRIVE
(
    PK_ID                    VARCHAR2(20) NOT NULL ENABLE,
    CLIENT_ID                VARCHAR2(255) NOT NULL ENABLE,
    CLIENT_EMAIL             VARCHAR2(255) NOT NULL ENABLE,
    PROJECT_ID               VARCHAR2(255),
    SUBSCRIBER_ID            VARCHAR2(255) NOT NULL ENABLE,
    SUBSCRIBER_TYPE          VARCHAR2(255),
    FILE_TYPE                VARCHAR2(255),
    IN_DIRECTORY             VARCHAR2(255),
    INBOUND_CONNECTION_TYPE  VARCHAR2(255),
    OUT_DIRECTORY            VARCHAR2(255),
    OUTBOUND_CONNECTION_TYPE VARCHAR2(255),
    POOLING_INTERVAL_MINS    VARCHAR2(255) NOT NULL ENABLE,
    DELETE_AFTER_COLLECTION  VARCHAR2(255) DEFAULT 'N',
    IS_ACTIVE                VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO              VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY               VARCHAR2(255),
    LAST_UPDATED_BY          VARCHAR2(255),
    LAST_UPDATED_DT          TIMESTAMP(6),
    CREDENTIAL_DIR           VARCHAR2(255),
    AUTH_JSON                CLOB,
    PRIMARY KEY (PK_ID)
);
