--------------------------------------------------------
--  DML for Table PETPE_PEM_TEMP
--------------------------------------------------------
CREATE TABLE PETPE_PEM_TEMP
    ( PROCESS_DOC_PK_ID VARCHAR2(30) NOT NULL ENABLE,
        SEQ_ID VARCHAR2(20) ,
		PARTNER_PROFILE VARCHAR2(30),
		APPLICATION_PROFILE VARCHAR2(30) ,
		SEQ_TYPE VARCHAR2(20) ,
		FILE_NAME VARCHAR2(100) ,
		FLOW_TYPE VARCHAR2(20) ,
		DOC_TYPE VARCHAR2(20) ,
		SENDER_ID VARCHAR2(100) ,
		RECEIVER_ID VARCHAR2(100), 
		TRANSACTION VARCHAR2(20), PRIMARY KEY (PROCESS_DOC_PK_ID)
    );
