--------------------------------------------------------
--  DDL for Table PETPE_SO_AS2
--------------------------------------------------------
CREATE TABLE PETPE_SO_AS2
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE),
    SUBSCRIBER_ID VARCHAR2(20 BYTE),
    AS2_IDENTIFIER VARCHAR2(50 BYTE),
    URL VARCHAR2(250 BYTE),
    SENDER_ID VARCHAR2(50 BYTE),
    SENDER_QUALIFIER VARCHAR2(10 BYTE),
    PAYLOAD_SECURITY VARCHAR2(30 BYTE),
    PAYLOAD_ENCRYPTION_ALGORITHM VARCHAR2(50 BYTE),
    IS_HTTPS VARCHAR2(1 BYTE) DEFAULT 'N',
    USERNAME VARCHAR2(50 BYTE),
    PASSWORD VARCHAR2(50 BYTE),
    SSL_TYPE VARCHAR2(10 BYTE),
    ENCRYPTION_ALGORITHM VARCHAR2(50 BYTE),
    SIGNATURE_ALGORITHM VARCHAR2(15 BYTE),
    IS_MDN_REQUIRED VARCHAR2(1 BYTE) DEFAULT 'N',
    MDN_TYPE VARCHAR2(15 BYTE),
    MDN_ENCRYPTION VARCHAR2(10 BYTE),
    RECEIPT_TO_ADDRESS VARCHAR2(50 BYTE),
    IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y',
    CREATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_FILESYSTEM
--------------------------------------------------------
CREATE TABLE PETPE_SO_FILESYSTEM
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    FSA_ADAPTER VARCHAR2(100 BYTE) NOT NULL ENABLE,
    IN_DIRECTORY VARCHAR2(200 BYTE),
    OUT_DIRECTORY VARCHAR2(200 BYTE),
    FILE_TYPE VARCHAR2(50 BYTE),
    DELETE_AFTER_COLLECTION VARCHAR2(1 BYTE)  DEFAULT 'N' NOT NULL ENABLE,
    POOLING_INTERVAL_MINS VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_FTP
--------------------------------------------------------
CREATE TABLE PETPE_SO_FTP
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROTOCOL_TYPE VARCHAR2(10 BYTE) NOT NULL ENABLE,
    HOST_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    PORT_NO VARCHAR2(6 BYTE) NOT NULL ENABLE,
    USER_ID VARCHAR2(200 BYTE) NOT NULL ENABLE,
    PASSWORD VARCHAR2(50 BYTE),
    IN_DIRECTORY VARCHAR2(200 BYTE),
    OUT_DIRECTORY VARCHAR2(200 BYTE),
    FILE_TYPE VARCHAR2(50 BYTE),
    DELETE_AFTER_COLLECTION VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    TRANSFER_TYPE VARCHAR2(10 BYTE) NOT NULL ENABLE,
    POOLING_INTERVAL_MINS VARCHAR2(10 BYTE) NOT NULL ENABLE,
    CERTIFICATE_ID VARCHAR2(100 BYTE) NOT NULL ENABLE,
    KNOWN_HOST_KEY VARCHAR2(100 BYTE),
    IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    USER_IDENTITY_KEY VARCHAR2(120 BYTE),
    ADAPTER_NAME VARCHAR2(200 BYTE) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_HTTP
--------------------------------------------------------
CREATE TABLE PETPE_SO_HTTP
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROTOCOL_TYPE VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IN_MAILBOX VARCHAR2(50 BYTE),
    OUTBOUND_URL VARCHAR2(200 BYTE),
    CERTIFICATE VARCHAR2(200 BYTE) NOT NULL ENABLE,
    IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_MAILBOX
--------------------------------------------------------
CREATE TABLE PETPE_SO_MAILBOX
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROTOCOL_TYPE VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IN_MAILBOX VARCHAR2(50 BYTE),
    OUT_MAILBOX VARCHAR2(50 BYTE),
    POOLING_INTERVAL_MINS VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IS_ACTIVE VARCHAR2(1 BYTE)  DEFAULT 'Y' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_MQ
--------------------------------------------------------
CREATE TABLE PETPE_SO_MQ
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    QUEUE_MANAGER VARCHAR2(50 BYTE) NOT NULL ENABLE,
    QUEUE_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    POOLING_INTERVAL_MINS VARCHAR2(10 BYTE) NOT NULL ENABLE,
    FILE_TYPE VARCHAR2(20 BYTE),
    IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    HOST_NAME VARCHAR2(100 BYTE) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_SAP
--------------------------------------------------------
CREATE TABLE PETPE_SO_SAP
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SAP_ROUTE VARCHAR2(30 BYTE) NOT NULL ENABLE,
    SAP_ADAPTER_NAME VARCHAR2(30 BYTE) NOT NULL ENABLE,
    IS_ACTIVE VARCHAR2(1 BYTE)  DEFAULT 'Y' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_WEBSERVICE
--------------------------------------------------------
CREATE TABLE PETPE_SO_WEBSERVICE
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    WEBSERVICE_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6), PRIMARY KEY (PK_ID)
   );

