--------------------------------------------------------
--  DDL for Table PETPE_SO_USERS
--------------------------------------------------------
CREATE TABLE PETPE_SO_USERS
   (    USERID VARCHAR2(30 BYTE) NOT NULL ENABLE,
    PASSWORD VARCHAR2(100 BYTE) NOT NULL ENABLE,
    ROLE VARCHAR2(50 BYTE) DEFAULT 'user' NOT NULL ENABLE,
    FIRST_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    MIDDLE_NAME VARCHAR2(50 BYTE),
    LAST_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    EMAIL VARCHAR2(100 BYTE) NOT NULL ENABLE,
    PHONE VARCHAR2(15 BYTE) NOT NULL ENABLE,
    STATUS VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    ONBOARDING_REF VARCHAR2(20 BYTE),
    PARTNER_REF CLOB,
    GROUP_REF CLOB,
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    IS_B2B_USER VARCHAR2(1 BYTE),
    IS_FAX_USER VARCHAR2(1 BYTE) , PRIMARY KEY (USERID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_SO_TPUSERS
--------------------------------------------------------
CREATE TABLE PETPE_SO_TPUSERS
   (    USERID VARCHAR2(30 BYTE) NOT NULL ENABLE,
    PARTNER_LIST CLOB,
    GROUP_LIST CLOB,
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6), PRIMARY KEY (USERID)
    );


--------------------------------------------------------
--  DDL for Table PETPE_SO_TPGROUPS
--------------------------------------------------------
CREATE TABLE PETPE_SO_TPGROUPS
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    GROUPNAME VARCHAR2(30 BYTE) NOT NULL ENABLE,
    PARTNER_LIST CLOB,
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6), PRIMARY KEY (PK_ID)
    );

--------------------------------------------------------
--  DDL for Table PETPE_SO_ONBOARDING
--------------------------------------------------------
CREATE TABLE PETPE_SO_ONBOARDING
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    EMAIL VARCHAR2(250 BYTE) NOT NULL ENABLE,
    TP_NAME VARCHAR2(30 BYTE) NOT NULL ENABLE,
    PROTOCOL VARCHAR2(10 BYTE) NOT NULL ENABLE,
    PROTOCOL_REF VARCHAR2(20 BYTE) NOT NULL ENABLE,
    VALIDATION_KEY VARCHAR2(30 BYTE) NOT NULL ENABLE,
    STATUS VARCHAR2(20 BYTE) DEFAULT 'InfoRequested' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DATE TIMESTAMP (6) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    GROUP_REF VARCHAR2(20 BYTE), PRIMARY KEY (PK_ID)
    );

