--------------------------------------------------------
--  DDL for Table PETPE_CD
--------------------------------------------------------
--RENAME TABLE PETPE_CD TO PETPE_SFG_CD;

ALTER TABLE PETPE_CD RENAME TO PETPE_SFG_CD;

CREATE TABLE PETPE_CD
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    REMOTE_HOST VARCHAR2(255 BYTE) NOT NULL ENABLE,
	REMOTE_PORT VARCHAR2(10 BYTE) NOT NULL ENABLE,
	REMOTE_USER VARCHAR2(255 BYTE),
	REMOTE_PASSWORD VARCHAR2(50 BYTE),
	TRANSFER_TYPE VARCHAR2(20 BYTE),
	LOCAL_NODE_NAME VARCHAR2(255 BYTE),
	REMOTE_NODE_NAME VARCHAR2(255 BYTE),
	CODE_PAGE_FROM VARCHAR2(20 BYTE),
    CODE_PAGE_TO VARCHAR2(20 BYTE),
	LOCAL_XLATE VARCHAR2(255 BYTE),
	DCB VARCHAR2(255 BYTE),
	SYS_OPTS VARCHAR2(255 BYTE),
	SECURITY_PROTOCOL VARCHAR2(100 BYTE),
	SECURE_PLUS VARCHAR2(100 BYTE),
	CA_CERTIFICATE VARCHAR2(100 BYTE),
	CIPHER_SUITS VARCHAR2(555 BYTE),
	ADAPTER_NAME VARCHAR2(100 BYTE),
	POLLING_INTERVAL VARCHAR2(20 BYTE),
	IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    IS_HUB_INFO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY VARCHAR2(100 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(100 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

UPDATE PETPE_TRADINGPARTNER SET TP_PROTOCOL  = 'SFG_CONNECT_DIRECT' WHERE TP_PROTOCOL  = 'Connect:Direct';
UPDATE PETPE_APPLICATION SET APP_INTEGRATION_PROTOCOL  = 'SFG_CONNECT_DIRECT' WHERE APP_INTEGRATION_PROTOCOL  = 'Connect:Direct';
COMMIT;

--------------------------------------------------------
--  DDL for Table PETPE_FTP
--------------------------------------------------------
ALTER TABLE PETPE_FTP MODIFY TRANSFER_TYPE NULL;
ALTER TABLE PETPE_FTP ADD CWD_UP VARCHAR2(20);
ALTER TABLE PETPE_FTP ADD QUOTE VARCHAR2(255);
ALTER TABLE PETPE_FTP ADD SITE VARCHAR2(255);
ALTER TABLE PETPE_FTP ADD CONNECTION_TYPE VARCHAR2(15);
ALTER TABLE PETPE_FTP ADD MB_DESTINATION VARCHAR2(255);
ALTER TABLE PETPE_FTP ADD MB_DESTINATION_LOOKUP VARCHAR2(50);
ALTER TABLE PETPE_FTP ADD SSL_SOCKET VARCHAR2(40);
ALTER TABLE PETPE_FTP ADD SSL_CIPHER VARCHAR2(255);
ALTER TABLE PETPE_FTP ADD SSH_AUTHENTICATION VARCHAR2(40);
ALTER TABLE PETPE_FTP ADD SSH_CIPHER VARCHAR2(40);
ALTER TABLE PETPE_FTP ADD SSH_COMPRESSION VARCHAR2(40);
ALTER TABLE PETPE_FTP ADD SSH_MAC VARCHAR2(40);
ALTER TABLE PETPE_FTP ADD SSH_IDENTITY_KEY_ID VARCHAR2(255);
