--------------------------------------------------------
--  DDL STATEMENT
--------------------------------------------------------
ALTER TABLE PETPE_TRANSFERINFO DROP (FA_DTM, DLE_DTM);

ALTER TABLE PETPE_TRANSFERINFO
  ADD (FA_DTM VARCHAR2(15),
	DLE_DTM VARCHAR2(15));

CREATE INDEX FA_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (FA_DTM);
CREATE INDEX DLE_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (DLE_DTM);