--------------------------------------------------------
--  DDL for Table PETPE_AS2
--------------------------------------------------------
CREATE TABLE PETPE_AS2
(
    PK_ID                        VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE              VARCHAR2(5 BYTE),
    SUBSCRIBER_ID                VARCHAR2(20 BYTE),
    AS2_IDENTIFIER               VARCHAR2(50 BYTE) NOT NULL ENABLE,
    URL                          VARCHAR2(250 BYTE),
    SENDER_ID                    VARCHAR2(50 BYTE),
    SENDER_QUALIFIER             VARCHAR2(10 BYTE),
    PAYLOAD_SECURITY             VARCHAR2(30 BYTE) DEFAULT 'Plain Text',
    PAYLOAD_ENCRYPTION_ALGORITHM VARCHAR2(50 BYTE) DEFAULT 'Triple DES 168 CBC with PKCS5 padding',
    IS_HTTPS                     VARCHAR2(10 BYTE) DEFAULT 'N',
    USERNAME                     VARCHAR2(50 BYTE),
    PASSWORD                     VARCHAR2(50 BYTE),
    SSL_TYPE                     VARCHAR2(250 BYTE) DEFAULT 'SSL_NONE',
    ENCRYPTION_ALGORITHM         VARCHAR2(50 BYTE) DEFAULT 'Triple DES 168 CBC with PKCS5 padding',
    SIGNATURE_ALGORITHM          VARCHAR2(10 BYTE) DEFAULT 'MD5',
    IS_MDN_REQUIRED              VARCHAR2(10 BYTE) DEFAULT 'Y',
    MDN_TYPE                     VARCHAR2(15 BYTE) DEFAULT '0',
    MDN_ENCRYPTION               VARCHAR2(10 BYTE) DEFAULT 'NONE',
    RECEIPT_TO_ADDRESS           VARCHAR2(50 BYTE),
    IS_ACTIVE                    VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO                  VARCHAR2(1 BYTE) DEFAULT 'N',
    CREATED_BY                   VARCHAR2(15 BYTE),
    LAST_UPDATED_BY              VARCHAR2(15 BYTE),
    LAST_UPDATED_DT              TIMESTAMP(6),
    ORG_AS2_ID                   VARCHAR2(256 BYTE),
    PARENT_MBX                   VARCHAR2(256 BYTE),
    HTTP_CLIENT_ADAPTER          VARCHAR2(256 BYTE),
    ERROR_DIR                    VARCHAR2(256 BYTE),
    IDENTITY_NAME                VARCHAR2(100 BYTE),
    PROFILE_NAME                 VARCHAR2(100 BYTE),
    KEY_CERT_PASSPHRASE          VARCHAR2(100 BYTE),
    CIPHER_STRENGTH              VARCHAR2(100 BYTE) DEFAULT 'ALL',
    PAYLOAD_TYPE                 VARCHAR2(50 BYTE) DEFAULT '0',
    MIME_TYPE                    VARCHAR2(50 BYTE) DEFAULT 'Application',
    MIME_SUB_TYPE                VARCHAR2(50 BYTE) DEFAULT 'plain',
    COMPRESS_DATA                VARCHAR2(5 BYTE) DEFAULT 'Y',
    EMAIL_ADDRESS                VARCHAR2(150 BYTE),
    EMAIL_HOST                   VARCHAR2(50 BYTE),
    EMAIL_PORT                   VARCHAR2(10 BYTE),
    RESPONSE_TIMEOUT             VARCHAR2(15 BYTE) DEFAULT '5',
    KEY_CERT                     VARCHAR2(255 BYTE),
    KEY_CERT_PATH                VARCHAR2(255 BYTE),
    CA_CERT                      VARCHAR2(255 BYTE),
    CA_CERT_PATH                 VARCHAR2(255 BYTE),
    EXCHG_CERT                   VARCHAR2(255 BYTE),
    EXCHG_CERT_PATH              VARCHAR2(255 BYTE),
    SIGNING_CERT                 VARCHAR2(255 BYTE),
    SIGNING_CERT_PATH            VARCHAR2(255 BYTE),
    SYS_CERT                     VARCHAR2(256 BYTE),
    RETRY_INTERVAL               VARCHAR2(10 BYTE) DEFAULT '5',
    NO_OF_RETRIES                VARCHAR2(10 BYTE) DEFAULT '5',
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_FILESYSTEM
--------------------------------------------------------
CREATE TABLE PETPE_FILESYSTEM
(
    PK_ID                   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE         VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID           VARCHAR2(20 BYTE) NOT NULL ENABLE,
    FSA_ADAPTER             VARCHAR2(100 BYTE) NOT NULL ENABLE,
    IN_DIRECTORY            VARCHAR2(200 BYTE),
    OUT_DIRECTORY           VARCHAR2(200 BYTE),
    FILE_TYPE               VARCHAR2(50 BYTE),
    DELETE_AFTER_COLLECTION VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    POOLING_INTERVAL_MINS   VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IS_ACTIVE               VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO             VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY              VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY         VARCHAR2(15 BYTE),
    LAST_UPDATED_DT         TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);


--------------------------------------------------------
--  DDL for Table PETPE_FTP
--------------------------------------------------------
CREATE TABLE PETPE_FTP
(
    PK_ID                   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE         VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID           VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROTOCOL_TYPE           VARCHAR2(10 BYTE) NOT NULL ENABLE,
    HOST_NAME               VARCHAR2(100 BYTE) NOT NULL ENABLE,
    PORT_NO                 VARCHAR2(6 BYTE) NOT NULL ENABLE,
    USER_ID                 VARCHAR2(200 BYTE) NOT NULL ENABLE,
    PASSWORD                VARCHAR2(50 BYTE),
    IN_DIRECTORY            VARCHAR2(200 BYTE),
    OUT_DIRECTORY           VARCHAR2(200 BYTE),
    FILE_TYPE               VARCHAR2(50 BYTE),
    DELETE_AFTER_COLLECTION VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    TRANSFER_TYPE           VARCHAR2(10 BYTE) NOT NULL ENABLE,
    POOLING_INTERVAL_MINS   VARCHAR2(10 BYTE) NOT NULL ENABLE,
    CERTIFICATE_ID          VARCHAR2(100 BYTE) NOT NULL ENABLE,
    KNOWN_HOST_KEY          VARCHAR2(100 BYTE),
    IS_ACTIVE               VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO             VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY              VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY         VARCHAR2(15 BYTE),
    LAST_UPDATED_DT         TIMESTAMP(6),
    USER_IDENTITY_KEY       VARCHAR2(120 BYTE),
    ADAPTER_NAME            VARCHAR2(200 BYTE) NOT NULL ENABLE,
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_HTTP
--------------------------------------------------------
CREATE TABLE PETPE_HTTP
(
    PK_ID           VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROTOCOL_TYPE   VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IN_MAILBOX      VARCHAR2(50 BYTE) NOT NULL ENABLE,
    OUTBOUND_URL    VARCHAR2(200 BYTE),
    CERTIFICATE     VARCHAR2(200 BYTE) NOT NULL ENABLE,
    IS_ACTIVE       VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO     VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_MAILBOX
--------------------------------------------------------
CREATE TABLE PETPE_MAILBOX
(
    PK_ID                 VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE       VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID         VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROTOCOL_TYPE         VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IN_MAILBOX            VARCHAR2(200 BYTE),
    OUT_MAILBOX           VARCHAR2(200 BYTE),
    POOLING_INTERVAL_MINS VARCHAR2(10 BYTE) NOT NULL ENABLE,
    IS_ACTIVE             VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO           VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY            VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY       VARCHAR2(15 BYTE),
    LAST_UPDATED_DT       TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_MQ
--------------------------------------------------------
CREATE TABLE PETPE_MQ
(
    PK_ID                 VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE       VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID         VARCHAR2(20 BYTE) NOT NULL ENABLE,
    QUEUE_MANAGER         VARCHAR2(50 BYTE) NOT NULL ENABLE,
    QUEUE_NAME            VARCHAR2(50 BYTE) NOT NULL ENABLE,
    POOLING_INTERVAL_MINS VARCHAR2(10 BYTE) NOT NULL ENABLE,
    FILE_TYPE             VARCHAR2(20 BYTE),
    IS_ACTIVE             VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO           VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY            VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY       VARCHAR2(15 BYTE),
    LAST_UPDATED_DT       TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_SAP
--------------------------------------------------------
CREATE TABLE PETPE_SAP
(
    PK_ID            VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE  VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID    VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SAP_ROUTE        VARCHAR2(30 BYTE) NOT NULL ENABLE,
    SAP_ADAPTER_NAME VARCHAR2(30 BYTE) NOT NULL ENABLE,
    IS_ACTIVE        VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO      VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY       VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY  VARCHAR2(15 BYTE),
    LAST_UPDATED_DT  TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_SFG_FTP
--------------------------------------------------------
CREATE TABLE PETPE_SFG_FTP
(
    PK_ID                   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE         VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID           VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROTOCOL_TYPE           VARCHAR2(10 BYTE) NOT NULL ENABLE,
    PROFILE_ID              VARCHAR2(100 BYTE),
    USER_ID                 VARCHAR2(200 BYTE),
    PASSWORD                VARCHAR2(50 BYTE),
    IN_DIRECTORY            VARCHAR2(200 BYTE),
    OUT_DIRECTORY           VARCHAR2(200 BYTE),
    FILE_TYPE               VARCHAR2(50 BYTE),
    DELETE_AFTER_COLLECTION VARCHAR2(1 BYTE) DEFAULT 'N',
    TRANSFER_TYPE           VARCHAR2(10 BYTE),
    POOLING_INTERVAL_MINS   VARCHAR2(10 BYTE) NOT NULL ENABLE,
    CERTIFICATE_ID          VARCHAR2(100 BYTE),
    KNOWN_HOST_KEY          VARCHAR2(100 BYTE),
    IS_ACTIVE               VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO             VARCHAR2(1 BYTE) DEFAULT 'N',
    CREATED_BY              VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY         VARCHAR2(15 BYTE),
    LAST_UPDATED_DT         TIMESTAMP(6),
    USER_IDENTITY_KEY       VARCHAR2(120 BYTE),
    ADAPTER_NAME            VARCHAR2(200 BYTE),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_EC
--------------------------------------------------------
CREATE TABLE PETPE_EC
(
    PK_ID           VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    EC_PROTOCOL     VARCHAR2(50 BYTE),
    EC_PROTOCOL_REF VARCHAR2(50 BYTE),
    IS_ACTIVE       VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO     VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_WEBSERVICE
--------------------------------------------------------
CREATE TABLE PETPE_WEBSERVICE
(
    PK_ID           VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID   VARCHAR2(20 BYTE) NOT NULL ENABLE,
    WEBSERVICE_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    IS_ACTIVE       VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
    IS_HUB_INFO     VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY      VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_SMTP
--------------------------------------------------------
CREATE TABLE PETPE_SMTP
(
    PK_ID                  VARCHAR2(20 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_TYPE        VARCHAR2(5 BYTE) NOT NULL ENABLE,
    SUBSCRIBER_ID          VARCHAR2(20 BYTE) NOT NULL ENABLE,
    NAME                   VARCHAR2(100 BYTE),
    ACCESS_PROTOCOL        VARCHAR2(50 BYTE),
    MAIL_SERVER            VARCHAR2(50 BYTE),
    MAIL_SERVER_PORT       VARCHAR2(50 BYTE),
    USER_NAME              VARCHAR2(100 BYTE),
    PASSWORD               VARCHAR2(50 BYTE),
    CONNECTION_RETRIES     VARCHAR2(50 BYTE),
    RETRY_INTERVAL         VARCHAR2(50 BYTE),
    MAX_MSGS_SESSION       VARCHAR2(50 BYTE),
    REMOVE_INBOX_MAIL_MSGS VARCHAR2(100 BYTE),
    SSL                    VARCHAR2(100 BYTE),
    KEY_CERT_PASS_PHRASE   VARCHAR2(50 BYTE),
    CIPHER_STRENGTH        VARCHAR2(50 BYTE),
    KEY_CERT               VARCHAR2(50 BYTE),
    CA_CERTIFICATES        VARCHAR2(50 BYTE),
    URI_NAME               VARCHAR2(50 BYTE),
    POOLING_INTERVAL       VARCHAR2(50 BYTE),
    CREATED_BY             VARCHAR2(15 BYTE),
    LAST_UPDATED_BY        VARCHAR2(15 BYTE),
    LAST_UPDATED_DT        TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);


