--------------------------------------------------------
--  DML for Table PETPE_SO_USERS
--------------------------------------------------------
UPDATE PETPE_SO_USERS SET ROLE = 'super_admin' WHERE ROLE = 'admin';
UPDATE PETPE_SO_USERS SET ROLE = 'data_processor' WHERE ROLE = 'user';
UPDATE PETPE_SO_USERS SET ROLE = 'super_admin' WHERE ROLE = 'SUPER_ADMIN';
UPDATE PETPE_SO_USERS SET ROLE = 'admin' WHERE ROLE = 'ADMIN';
UPDATE PETPE_SO_USERS SET ROLE = 'on_boarder' WHERE ROLE = 'ON_BOARDER';
UPDATE PETPE_SO_USERS SET ROLE = 'business_admin' WHERE ROLE = 'BUSINESS_ADMIN';
UPDATE PETPE_SO_USERS SET ROLE = 'business_user' WHERE ROLE = 'BUSINESS_USER';
UPDATE PETPE_SO_USERS SET ROLE = 'data_processor' WHERE ROLE = 'DATA_PROCESSOR';
UPDATE PETPE_SO_USERS SET ROLE = 'data_processor_restricted' WHERE ROLE = 'DATA_PROCESSOR_RESTRICTED';

--------------------------------------------------------
--  DDL for PETPE_TRADINGPARTNER
--------------------------------------------------------
ALTER TABLE PETPE_TRADINGPARTNER ADD CUSTOM_TP_NAME VARCHAR2(255);
ALTER TABLE PETPE_TRADINGPARTNER ADD PGP_INFO VARCHAR2(255);
ALTER TABLE PETPE_TRADINGPARTNER ADD IP_WHITELIST VARCHAR2(255);
ALTER TABLE PETPE_TRADINGPARTNER ADD IS_ONLY_PCM VARCHAR2(1);

--------------------------------------------------------
--  DDL for PETPE_SO_USERS
--------------------------------------------------------
ALTER TABLE PETPE_SO_USERS  ADD OTP VARCHAR2(6);

--------------------------------------------------------
--  DDL for PETPE_CD
--------------------------------------------------------
--ALTER TABLE PETPE_CD ADD OPERATING_SYSTEM VARCHAR2(20 BYTE);
--ALTER TABLE PETPE_CD ADD HOST_NAME VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD PORT VARCHAR2(10 BYTE);
--ALTER TABLE PETPE_CD ADD COPY_SIS_OPTS VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD CHECK_POINT VARCHAR2(10 BYTE);
--ALTER TABLE PETPE_CD ADD COMPRESSION_LEVEL VARCHAR2(2 BYTE);
--ALTER TABLE PETPE_CD ADD DISPOSITION VARCHAR2(10 BYTE);
--ALTER TABLE PETPE_CD ADD SUBMIT VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD SECURE VARCHAR2(1 BYTE);
--ALTER TABLE PETPE_CD ADD RUN_JOB VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD RUN_TASK VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD CA_CERTIFICATE VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD CIPHER_SUITS VARCHAR2(2000 BYTE);
--ALTER TABLE PETPE_CD ADD DCB_PARAM VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD DNS_NAME VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD UNIT VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD STORAGE_CLASS VARCHAR2(255 BYTE);
--ALTER TABLE PETPE_CD ADD SPACE VARCHAR2(255 BYTE);

--------------------------------------------------------
--  DDL for PETPE_AWS_S3
--------------------------------------------------------
CREATE TABLE PETPE_AWS_S3
    ( PK_ID VARCHAR2(20) NOT NULL,
      SUBSCRIBER_TYPE VARCHAR2(5) NOT NULL,
      SUBSCRIBER_ID VARCHAR2(20) NOT NULL,
      SOURCE_PATH VARCHAR2(255),
      BUCKET_NAME VARCHAR2(255) NOT NULL,
      FILE_NAME VARCHAR2(255),
      ACCESS_KEY VARCHAR2(255) NOT NULL,
      SECRET_KEY VARCHAR2(255) NOT NULL,
      ENDPOINT VARCHAR2(255),
      REGION VARCHAR2(255),
      ADAPTER_NAME VARCHAR2(200),
      POOLING_INTERVAL_MINS VARCHAR2(10) NOT NULL,
      IN_MAILBOX VARCHAR2(255),
      FILE_TYPE VARCHAR2(100 BYTE),
      IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
      IS_HUB_INFO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
      CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
      LAST_UPDATED_BY VARCHAR2(15 BYTE),
      LAST_UPDATED_DT TIMESTAMP (6), PRIMARY KEY (PK_ID)
    );


--------------------------------------------------------
--  DDL for PETPE_AWS_S3
--------------------------------------------------------

--DROP TABLE PETPE_CD;

CREATE TABLE PETPE_CD
    ( PK_ID VARCHAR2(20) NOT NULL,
      SUBSCRIBER_TYPE VARCHAR2(5) NOT NULL,
      SUBSCRIBER_ID VARCHAR2(20) NOT NULL,
      LOCAL_NODE_NAME VARCHAR2(255),
      REMOTE_FILE_NAME VARCHAR2(255),
      NODE_NAME VARCHAR2(255),
      SNODE_ID VARCHAR2(255),
      SNODE_ID_PASSWORD VARCHAR2(255),
      OPERATING_SYSTEM VARCHAR2(255),
      DIRECTORY VARCHAR2(255),
      HOST_NAME VARCHAR2(200),
      PORT VARCHAR2(50),
      COPY_SIS_OPTS VARCHAR2(255),
      CHECK_POINT VARCHAR2(100 BYTE),
      COMPRESSION_LEVEL VARCHAR2(255),
      DISPOSITION VARCHAR2(255),
      SUBMIT VARCHAR2(200),
      SECURE VARCHAR2(10) ,
      RUN_JOB VARCHAR2(255),
      RUN_TASK VARCHAR2(100 BYTE),
      CA_CERTIFICATE_NAME VARCHAR2(255),
      CIPHER_SUITS CLOB,
      DCB_PARAM VARCHAR2(255),
      DNS_NAME VARCHAR2(255),
      UNIT VARCHAR2(255),
      STORAGE_CLASS VARCHAR2(255),
      SECURITY_PROTOCOL VARCHAR2(255),
      SPACE VARCHAR2(255),
      ADAPTER_NAME VARCHAR2(200),
      POOLING_INTERVAL_MINS VARCHAR2(10),
      IS_ACTIVE VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL ENABLE,
      IS_HUB_INFO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
      CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
      LAST_UPDATED_BY VARCHAR2(15 BYTE),
      LAST_UPDATED_DT TIMESTAMP (6), PRIMARY KEY (PK_ID)
    );

CREATE SEQUENCE SEQ_PETPE_PEM_GEN  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 10 NOORDER  NOCYCLE ;

ALTER TABLE PETPE_SFG_FTP ADD PRF_AUTH_TYPE VARCHAR2(15);

ALTER TABLE PETPE_PROCESSDOCS MODIFY PROCESS_RULESEQ VARCHAR2(2000);
