--------------------------------------------------------
--  DDL for Table PETPE_TRADINGPARTNER
--------------------------------------------------------
CREATE TABLE PETPE_TRADINGPARTNER
(
    PK_ID                VARCHAR2(20 BYTE) NOT NULL ENABLE,
    TP_NAME              VARCHAR2(200 BYTE) NOT NULL ENABLE,
    TP_ID                VARCHAR2(200 BYTE) NOT NULL ENABLE,
    ADDRESS_LINE1        VARCHAR2(100 BYTE),
    ADDRESS_LINE2        VARCHAR2(100 BYTE),
    EMAIL                VARCHAR2(250 BYTE) NOT NULL ENABLE,
    PHONE                VARCHAR2(15 BYTE) NOT NULL ENABLE,
    TP_PROTOCOL          VARCHAR2(20 BYTE) NOT NULL ENABLE,
    TP_PICKUP_FILES      VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    FILE_TP_SERVER       VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    PARTNER_PROTOCOL_REF VARCHAR2(20 BYTE) NOT NULL ENABLE,
    TP_IS_ACTIVE         VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    IS_PROTOCOL_HUB_INFO VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    CREATED_BY           VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY      VARCHAR2(15 BYTE),
    LAST_UPDATED_DT      TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_TP_ACTIVITY_HISTORY
--------------------------------------------------------
CREATE TABLE PETPE_TP_ACTIVITY_HISTORY
(
    PK_ID       VARCHAR2(50 BYTE) NOT NULL ENABLE,
    TP_REF_ID   VARCHAR2(30 BYTE),
    USER_NAME   VARCHAR2(100 BYTE) NOT NULL ENABLE,
    USER_ID     VARCHAR2(15 BYTE) NOT NULL ENABLE,
    ACTIVITY_DT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    ACTIVITY    CLOB,
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_TRADINGPARTNER_SFG
--------------------------------------------------------
CREATE TABLE PETPE_TRADINGPARTNER_SFG
(
    PK_ID                VARCHAR2(20 BYTE) NOT NULL ENABLE,
    TP_NAME              VARCHAR2(200 BYTE) NOT NULL ENABLE,
    TP_ID                VARCHAR2(200 BYTE) NOT NULL ENABLE,
    ADDRESS_LINE1        VARCHAR2(100 BYTE),
    ADDRESS_LINE2        VARCHAR2(100 BYTE),
    EMAIL                VARCHAR2(250 BYTE) NOT NULL ENABLE,
    PHONE                VARCHAR2(15 BYTE) NOT NULL ENABLE,
    TP_PROTOCOL          VARCHAR2(20 BYTE) NOT NULL ENABLE,
    TP_PICKUP_FILES      VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    FILE_TP_SERVER       VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    PARTNER_PROTOCOL_REF VARCHAR2(20 BYTE) NOT NULL ENABLE,
    TP_IS_ACTIVE         VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL ENABLE,
    IS_PROTOCOL_HUB_INFO VARCHAR2(1 BYTE) DEFAULT 'N',
    CREATED_BY           VARCHAR2(15 BYTE) NOT NULL ENABLE,
    LAST_UPDATED_BY      VARCHAR2(15 BYTE),
    LAST_UPDATED_DT      TIMESTAMP(6),
    PARTNER_PRIORITY     VARCHAR2(50 BYTE),
    PRIMARY KEY (PK_ID)
);
--------------------------------------------------------
--  DDL for Table PETPE_EDIPROPERTIES
--------------------------------------------------------
CREATE TABLE PETPE_EDIPROPERTIES
(
    PK_ID               VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PARTNERID           VARCHAR2(20 BYTE),
    PARTNERNAME         VARCHAR2(50 BYTE),
    DIRECTION           VARCHAR2(20 BYTE),
    VALIDATEINPUT       VARCHAR2(3 BYTE),
    VALIDATEOUTPUT      VARCHAR2(3 BYTE),
    ISASENDERIDQAL      VARCHAR2(5 BYTE),
    ISASENDERID         VARCHAR2(20 BYTE),
    ISARECEIVERIDQAL    VARCHAR2(5 BYTE),
    ISARECEIVERID       VARCHAR2(20 BYTE),
    ISACONTSTD          VARCHAR2(10 BYTE),
    ISAAUTHINFO         VARCHAR2(20 BYTE),
    ISAAUTHINFOQUAL     VARCHAR2(20 BYTE),
    ISAAUTHSECINFO      VARCHAR2(20 BYTE),
    ISAAUTHSECQUAL      VARCHAR2(20 BYTE),
    LIMITINTERSIZE      VARCHAR2(3 BYTE),
    GSSENDERID          VARCHAR2(20 BYTE),
    GSRECEIVERID        VARCHAR2(20 BYTE),
    FUNCATIONALIDCODE   VARCHAR2(20 BYTE),
    RESPAGENCYCODE      VARCHAR2(10 BYTE),
    GROUPVERSION        VARCHAR2(20 BYTE),
    STSENDERID          VARCHAR2(20 BYTE),
    STRECEIVERID        VARCHAR2(20 BYTE),
    LASTUPDATEDBY       VARCHAR2(40 BYTE),
    UPDATEDON           VARCHAR2(100 BYTE),
    INTERVERSION        VARCHAR2(20 BYTE),
    RETAINENV           VARCHAR2(20 BYTE),
    DATAEXTRACTION      VARCHAR2(30 BYTE),
    EXTRACTIONMAILBOX   VARCHAR2(150 BYTE),
    BATCHTRANSACTION    VARCHAR2(20 BYTE),
    COMPLCHECK          VARCHAR2(20 BYTE),
    COMPLCHECKMAP       VARCHAR2(150 BYTE),
    HIPPACOMPLIANCE     VARCHAR2(20 BYTE),
    HIPPAVALLEVEL       VARCHAR2(20 BYTE),
    BUSINESSPROCESS     VARCHAR2(200 BYTE),
    INVOKEBPFORISA      VARCHAR2(10 BYTE),
    EXPECTACK           VARCHAR2(10 BYTE),
    USECORRELATION      VARCHAR2(20 BYTE),
    ACCEPTLOOKALIAS     VARCHAR2(20 BYTE),
    ISAACCEPTLOOKALIAS  VARCHAR2(20 BYTE),
    INTACKREQ           VARCHAR2(10 BYTE),
    ERRORBP             VARCHAR2(150 BYTE),
    ACCEPTNONINTER      VARCHAR2(10 BYTE),
    SPOUTBOUNDENCODE    VARCHAR2(20 BYTE),
    TA1ALAFORM          VARCHAR2(100 BYTE),
    ALA999FORM          VARCHAR2(20 BYTE),
    GLOBALCONTNO        VARCHAR2(10 BYTE),
    ALAFORM997          VARCHAR2(20 BYTE),
    ACCNONGROUP         VARCHAR2(20 BYTE),
    ACKDETAILS          VARCHAR2(20 BYTE),
    EDIPOSTMODE         VARCHAR2(100 BYTE),
    USEINDICATOR        VARCHAR2(5 BYTE),
    ERRORBPMODE         VARCHAR2(10 BYTE),
    PERCONTNUMCHECK     VARCHAR2(10 BYTE),
    PERDUPNUMCHECK      VARCHAR2(20 BYTE),
    INVOKEBPMODE        VARCHAR2(20 BYTE),
    ACKOVERDUEHR        VARCHAR2(2 BYTE),
    ACKOVERDUEMIN       VARCHAR2(2 BYTE),
    ENCODEDOC           VARCHAR2(3 BYTE),
    SEGTERM             VARCHAR2(25 BYTE),
    SUBELETERM          VARCHAR2(25 BYTE),
    ELETERM             VARCHAR2(25 BYTE),
    RELEASECHAR         VARCHAR2(25 BYTE),
    GENINACK            VARCHAR2(15 BYTE),
    ACKDETLEVEL         VARCHAR2(25 BYTE),
    BPINVOKESETINPD     VARCHAR2(10 BYTE),
    EXTRACTIONMAILBOXBP VARCHAR2(200 BYTE),
    TRNSETIDCODE        VARCHAR2(10 BYTE),
    STREAMSEG           VARCHAR2(5 BYTE),
    ISAENVELOPEID       VARCHAR2(200 BYTE),
    ISAENVELOPENAME     VARCHAR2(200 BYTE),
    GSENVELOPEID        VARCHAR2(200 BYTE),
    GSENVELOPENAME      VARCHAR2(200 BYTE),
    STENVELOPEID        VARCHAR2(200 BYTE),
    STENVELOPENAME      VARCHAR2(200 BYTE),
    PRIMARY KEY (PK_ID)
);

--------------------------------------------------------
--  DDL for Table PETPE_PEM_CODE_LIST
--------------------------------------------------------
CREATE TABLE PETPE_PEM_CODE_LIST
(
    PK_ID                VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PROFILE_NAME         VARCHAR2(100 BYTE) NOT NULL ENABLE,
    PROTOCOL             VARCHAR2(20 BYTE),
    CORRELATION_VALUE_1  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_2  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_3  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_4  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_5  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_6  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_7  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_8  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_9  VARCHAR2(250 BYTE),
    CORRELATION_VALUE_10 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_11 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_12 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_13 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_14 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_15 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_16 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_17 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_18 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_19 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_20 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_21 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_22 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_23 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_24 VARCHAR2(250 BYTE),
    CORRELATION_VALUE_25 VARCHAR2(250 BYTE),
    PRIMARY KEY (PK_ID)
);
