--------------------------------------------------------
--  DDL for Table PETPE_OCR_BR
--------------------------------------------------------
CREATE TABLE PETPE_OCR_BR
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    BR_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    LOGIC VARCHAR2(100 BYTE) NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_DIGITAL_PARTNER
--------------------------------------------------------
CREATE TABLE PETPE_OCR_DIGITAL_PARTNER
   (    PARTNER_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PARTNER_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    EMAIL VARCHAR2(250 BYTE),
    PHONE VARCHAR2(15 BYTE),
    ENRICHMENT_REF VARCHAR2(200 BYTE),
    BUSINESS_RULES_REF VARCHAR2(200 BYTE),
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    APPLY_DEFAULT_ROUNTING VARCHAR2(1 BYTE) DEFAULT 'N',
    STATUS VARCHAR2(20 BYTE) DEFAULT 'ACTIVE' , PRIMARY KEY (PARTNER_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_EMAIL_ATTACHMENTS
--------------------------------------------------------
CREATE TABLE PETPE_OCR_EMAIL_ATTACHMENTS
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    EMAIL_REF_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    EMAIL_CONTENT_REF_ID VARCHAR2(50 BYTE),
    EMAIL_UID NUMBER(10,0),
    EMAIL_TYPE VARCHAR2(10 BYTE),
    ATTACHMENT_PATH VARCHAR2(1000 BYTE),
    ATTACHMENT_NAME VARCHAR2(200 BYTE),
    ACTIVITY_DT TIMESTAMP (6),
    OCR_PROCESSING VARCHAR2(1 BYTE) DEFAULT 'N',
    EMAIL_INDEX NUMBER(10,0) DEFAULT 0,
    ATTACHMENT_TYPE VARCHAR2(50 BYTE),
    CONTENT_ID VARCHAR2(200 BYTE) , PRIMARY KEY (PK_ID, EMAIL_REF_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_EMAIL_CONTENT
--------------------------------------------------------
CREATE TABLE PETPE_OCR_EMAIL_CONTENT
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    EMAIL_REF_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    EMAIL_UID NUMBER(10,0),
    EMAIL_TYPE VARCHAR2(10 BYTE),
    EMAIL_FROM VARCHAR2(320 BYTE),
    EMAIL_CONTENT CLOB,
    CONTENT_TYPE VARCHAR2(255 BYTE),
    ATTACHMENT_PATH VARCHAR2(1000 BYTE),
    ACTIVITY_DT TIMESTAMP (6),
    EMAIL_CC CLOB,
    EMAIL_BCC CLOB,
    EMAIL_TO CLOB,
    EMAIL_SUBJECT CLOB , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_EMAIL_SYNC_HISTORY
--------------------------------------------------------
CREATE TABLE PETPE_OCR_EMAIL_SYNC_HISTORY
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ACTIVITY_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    ACTIVITY CLOB,
    LAST_SYNC_UNTIL_UID NUMBER(10,0) DEFAULT 0 , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_ENRICHMENT
--------------------------------------------------------
 CREATE TABLE PETPE_OCR_ENRICHMENT
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ENRICHMENT_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    LOGIC VARCHAR2(100 BYTE) NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_PO
--------------------------------------------------------
CREATE TABLE PETPE_OCR_PO
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    QUEUE_REF VARCHAR2(300 BYTE),
    QUEUE_REF_NAME VARCHAR2(700 BYTE),
    PARTNER_REF VARCHAR2(50 BYTE),
    PARTNER_REF_NAME VARCHAR2(1000 BYTE),
    PO_ADDRESS_LINE1 VARCHAR2(1000 BYTE),
    PO_CITY VARCHAR2(1000 BYTE),
    PO_STATE VARCHAR2(1000 BYTE),
    PO_COUNTRY VARCHAR2(1000 BYTE),
    PO_ZIP VARCHAR2(1000 BYTE),
    PO_TOTAL NUMBER(19,4),
    PO_NUMBER VARCHAR2(30 BYTE),
    PO_ORDLINE_COMMENTS VARCHAR2(500 BYTE),
    ORDER_DATE VARCHAR2(50 BYTE),
    REQUESTED_SHIP_DATE VARCHAR2(35 BYTE),
    SOLD_TO_NAME VARCHAR2(200 BYTE),
    SOLD_TO_ACC_NO VARCHAR2(50 BYTE),
    SHIP_VIA_CARRIER VARCHAR2(100 BYTE),
    SHIP_VIA_ACCT_NO VARCHAR2(100 BYTE),
    SHIP_VIA_TERMS VARCHAR2(2000 BYTE),
    SHIP_VIA2_CARRIER VARCHAR2(100 BYTE),
    SHIP_VIA2_ACCT_NO VARCHAR2(100 BYTE),
    SHIP_VIA2_TERMS VARCHAR2(200 BYTE),
    SHIP_VIA3_CARRIER VARCHAR2(100 BYTE),
    SHIP_VIA3_ACCT_NO VARCHAR2(100 BYTE),
    SHIP_VIA3_TERMS VARCHAR2(200 BYTE),
    SPECIAL_INSTRNS VARCHAR2(200 BYTE),
    SHIPPING_INSTRNS VARCHAR2(500 BYTE),
    SHIPMENT_REF VARCHAR2(500 BYTE),
    CONTACT_NAME VARCHAR2(100 BYTE),
    CONTACT_PHONE VARCHAR2(15 BYTE),
    CONTACT_FAX VARCHAR2(15 BYTE),
    CONTACT_EMAIL VARCHAR2(250 BYTE),
    CONTACT_TRK_EMAIL VARCHAR2(250 BYTE),
    CONTACT_ACK_EMAIL VARCHAR2(250 BYTE),
    PO_CONFIDENCE_LEVEL NUMBER(11,0),
    OL_CONFIDENCE_LEVEL NUMBER(11,0),
    SOURCE_FILE VARCHAR2(500 BYTE),
    TEMPLATE_LIB VARCHAR2(50 BYTE),
    OCR_SKIP_PAGE NUMBER(11,0),
    PO_MATCHED_TEMPLATE VARCHAR2(50 BYTE),
    OL_MATCHED_TEMPLATE VARCHAR2(50 BYTE),
    PO_STATUS VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PO_STATUS_COMMENTS VARCHAR2(200 BYTE),
    PO_STATUS_STEP VARCHAR2(100 BYTE),
    PO_REVIEWER VARCHAR2(50 BYTE),
    PO_REVIEWER_COMMENTS VARCHAR2(500 BYTE),
    DD_TYPE VARCHAR2(10 BYTE),
    EMAIL_RECEIVED_DT TIMESTAMP (6),
    EMAIL_UID NUMBER(10,0),
    EMAIL_FROM VARCHAR2(320 BYTE),
    EMAIL_HAVE_ATTACHMENT VARCHAR2(1 BYTE) DEFAULT 'N',
    EMAIL_HAVE_FAX VARCHAR2(1 BYTE) DEFAULT 'N',
    EMAIL_REPLIED VARCHAR2(1 BYTE) DEFAULT 'N',
    EMAIL_FORWARDED VARCHAR2(1 BYTE) DEFAULT 'N',
    EMAIL_ARCHIVED VARCHAR2(1 BYTE) DEFAULT 'N',
    SUBMITTED_TO_ERP VARCHAR2(1 BYTE) DEFAULT 'N',
    EMAIL_STATUS_COMMENTS VARCHAR2(200 BYTE),
    EMAIL_STATUS_STEP VARCHAR2(100 BYTE),
    ERP_SUBMITTED_DT TIMESTAMP (6),
    CREATED_BY VARCHAR2(15 BYTE),
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    SO_NUMBER VARCHAR2(30 BYTE),
    SHIP_DATE VARCHAR2(35 BYTE),
    IS_ARCHIVED VARCHAR2(1 BYTE) DEFAULT 'N',
    PO_STATUS_PREVIOUS VARCHAR2(20 BYTE),
    EVENT_LOCKED VARCHAR2(1 BYTE) DEFAULT 'N',
    OCR_PARTNER_NAME VARCHAR2(50 BYTE),
    EMAIL_SYNC_FAIL_MSG VARCHAR2(2000 BYTE),
    EMAIL_TO CLOB,
    EMAIL_SUBJECT CLOB , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_PO_ADDRESS
--------------------------------------------------------
CREATE TABLE PETPE_OCR_PO_ADDRESS
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_REF_ID VARCHAR2(50 BYTE)  NOT NULL ENABLE,
    PO_NUMBER VARCHAR2(30 BYTE),
    NAME VARCHAR2(200 BYTE),
    ADDRESS_TYPE VARCHAR2(15 BYTE),
    ADDRESS_LINE1 VARCHAR2(100 BYTE),
    ADDRESS_LINE2 VARCHAR2(100 BYTE),
    CITY VARCHAR2(100 BYTE),
    ADDR_STATE VARCHAR2(50 BYTE),
    POSTAL_CODE VARCHAR2(15 BYTE),
    COUNTRY VARCHAR2(50 BYTE),
    CREATED_BY VARCHAR2(15 BYTE)  NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_PO_ADDRESS_EXT
--------------------------------------------------------
CREATE TABLE PETPE_OCR_PO_ADDRESS_EXT
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_REF_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_NUMBER VARCHAR2(30 BYTE),
    NAME VARCHAR2(200 BYTE),
    ADDRESS_TYPE VARCHAR2(15 BYTE),
    ADDRESS_LINE1 VARCHAR2(100 BYTE),
    ADDRESS_LINE2 VARCHAR2(100 BYTE),
    CITY VARCHAR2(100 BYTE),
    ADDR_STATE VARCHAR2(50 BYTE),
    POSTAL_CODE VARCHAR2(15 BYTE),
    COUNTRY VARCHAR2(50 BYTE),
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_PO_EXT
--------------------------------------------------------
CREATE TABLE PETPE_OCR_PO_EXT
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_ADDRESS_LINE1 VARCHAR2(100 BYTE),
    PO_CITY VARCHAR2(100 BYTE),
    PO_STATE VARCHAR2(100 BYTE) NOT NULL ENABLE,
    PO_COUNTRY VARCHAR2(50 BYTE),
    PO_ZIP VARCHAR2(15 BYTE),
    PO_NUMBER VARCHAR2(30 BYTE),
    PO_TOTAL NUMBER(19,4) DEFAULT 0.0 NOT NULL ENABLE,
    PO_ORDLINE_COMMENTS VARCHAR2(500 BYTE),
    ORDER_DATE VARCHAR2(50 BYTE),
    REQUESTED_SHIP_DATE VARCHAR2(35 BYTE),
    SOLD_TO_NAME VARCHAR2(200 BYTE),
    SOLD_TO_ACC_NO VARCHAR2(50 BYTE),
    SHIP_VIA_CARRIER VARCHAR2(100 BYTE),
    SHIP_VIA_ACCT_NO VARCHAR2(100 BYTE),
    SHIP_VIA_TERMS VARCHAR2(200 BYTE),
    SPECIAL_INSTRNS VARCHAR2(200 BYTE),
    SHIPPING_INSTRNS VARCHAR2(500 BYTE),
    SHIPMENT_REF VARCHAR2(500 BYTE),
    CONTACT_NAME VARCHAR2(100 BYTE),
    CONTACT_PHONE VARCHAR2(15 BYTE),
    CONTACT_FAX VARCHAR2(15 BYTE),
    CONTACT_EMAIL VARCHAR2(250 BYTE),
    CONTACT_TRK_EMAIL VARCHAR2(250 BYTE),
    CONTACT_ACK_EMAIL VARCHAR2(250 BYTE),
    MEMO_TO VARCHAR2(150 BYTE),
    MEMO_FROM VARCHAR2(150 BYTE),
    MEMO_COMPANY VARCHAR2(150 BYTE),
    MEMO_SUBJECT VARCHAR2(250 BYTE),
    MEMO_FAX VARCHAR2(150 BYTE),
    MEMO_DESC VARCHAR2(500 BYTE),
    PO_CONFIDENCE_LEVEL NUMBER(11,0),
    OL_CONFIDENCE_LEVEL NUMBER(11,0),
    SOURCE_FILE VARCHAR2(500 BYTE),
    TEMPLATE_LIB VARCHAR2(50 BYTE),
    OCR_SKIP_PAGE NUMBER(11,0)  DEFAULT -1 NOT NULL ENABLE,
    PO_MATCHED_TEMPLATE VARCHAR2(50 BYTE),
    OL_MATCHED_TEMPLATE VARCHAR2(50 BYTE),
    PO_STATUS VARCHAR2(20 BYTE),
    PO_STATUS_COMMENTS VARCHAR2(200 BYTE),
    PO_STATUS_STEP VARCHAR2(100 BYTE),
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    SHIP_VIA2_CARRIER VARCHAR2(100 BYTE),
    SHIP_VIA2_ACCT_NO VARCHAR2(100 BYTE),
    SHIP_VIA2_TERMS VARCHAR2(200 BYTE),
    SHIP_VIA3_CARRIER VARCHAR2(100 BYTE),
    SHIP_VIA3_ACCT_NO VARCHAR2(100 BYTE),
    SHIP_VIA3_TERMS VARCHAR2(200 BYTE),
    SO_NUMBER VARCHAR2(30 BYTE),
    SHIP_DATE VARCHAR2(35 BYTE),
    OCR_PARTNER_NAME VARCHAR2(50 BYTE) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_PO_ORDLINE
--------------------------------------------------------
CREATE TABLE PETPE_OCR_PO_ORDLINE
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_REF_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_NUMBER VARCHAR2(30 BYTE),
    LINE_NUMBER VARCHAR2(10 BYTE),
    ORD_QUANTITY VARCHAR2(50 BYTE),
    ORD_UOM VARCHAR2(50 BYTE),
    ITEM_NUMBER VARCHAR2(100 BYTE),
    DESCRIPTION VARCHAR2(500 BYTE),
    CUST_ITEM_NUMBER VARCHAR2(100 BYTE),
    UNIT_PRICE VARCHAR2(50 BYTE),
    PRICE_UOM VARCHAR2(50 BYTE),
    EXTENDED_PRICE VARCHAR2(50 BYTE),
    SPA VARCHAR2(50 BYTE),
    REQ_SHIP_DATE VARCHAR2(35 BYTE),
    SHIPPING_METHOD VARCHAR2(50 BYTE),
    ACCT VARCHAR2(50 BYTE),
    SHIPPING_TERMS VARCHAR2(50 BYTE),
    PAGE_NUMBER NUMBER(11,0),
    CONFIDENCE_LEVEL NUMBER(11,0) NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_PO_ORDLINE_EXT
--------------------------------------------------------
CREATE TABLE PETPE_OCR_PO_ORDLINE_EXT
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_REF_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_NUMBER VARCHAR2(30 BYTE),
    LINE_NUMBER VARCHAR2(10 BYTE),
    ORD_QUANTITY VARCHAR2(50 BYTE),
    ORD_UOM VARCHAR2(50 BYTE),
    ITEM_NUMBER VARCHAR2(100 BYTE),
    DESCRIPTION VARCHAR2(500 BYTE),
    CUST_ITEM_NUMBER VARCHAR2(100 BYTE),
    UNIT_PRICE VARCHAR2(50 BYTE),
    PRICE_UOM VARCHAR2(50 BYTE),
    EXTENDED_PRICE VARCHAR2(50 BYTE),
    SPA VARCHAR2(50 BYTE),
    REQ_SHIP_DATE VARCHAR2(35 BYTE),
    SHIPPING_METHOD VARCHAR2(50 BYTE),
    ACCT VARCHAR2(50 BYTE),
    SHIPPING_TERMS VARCHAR2(50 BYTE),
    PAGE_NUMBER NUMBER(11,0),
    CONFIDENCE_LEVEL NUMBER(11,0) NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_QUEUES
--------------------------------------------------------
CREATE TABLE PETPE_OCR_QUEUES
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    QUEUE_NAME VARCHAR2(50 BYTE) NOT NULL ENABLE,
    DESCRIPTION VARCHAR2(500 BYTE),
    CURRENT_LEVEL NUMBER(11,0),
    PARENT_QUEUES_REF VARCHAR2(300 BYTE) NOT NULL ENABLE,
    PARENT_QUEUES_NAMES VARCHAR2(700 BYTE),
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    IS_DEFAULT_QUEUE VARCHAR2(1 BYTE) DEFAULT 'N' , PRIMARY KEY (PK_ID, PARENT_QUEUES_REF)
   ) ;

--------------------------------------------------------
--  DDL for Table PETPE_OCR_QUEUESACCESS
--------------------------------------------------------
CREATE TABLE PETPE_OCR_QUEUESACCESS
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    USERID VARCHAR2(30 BYTE) NOT NULL ENABLE,
    QUEUE_REF VARCHAR2(300 BYTE) NOT NULL ENABLE,
    QUEUE_REF_NAME VARCHAR2(700 BYTE) NOT NULL ENABLE,
    ACCESS_LEVEL VARCHAR2(50 BYTE) NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_ROUTING
--------------------------------------------------------
CREATE TABLE PETPE_OCR_ROUTING
   (    ROUTING_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ROUTING_NAME1 VARCHAR2(100 BYTE) NOT NULL ENABLE,
    ROUTING_CONDITION1 VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ROUTING_VALUE1 VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    ROUTING_NAME2 VARCHAR2(100 BYTE),
    ROUTING_CONDITION2 VARCHAR2(20 BYTE),
    ROUTING_VALUE2 VARCHAR2(4000 BYTE),
    QUEUE_REF VARCHAR2(300 BYTE) NOT NULL ENABLE,
    QUEUE_REF_NAME VARCHAR2(700 BYTE) NOT NULL ENABLE,
    PARTNER_REF VARCHAR2(20 BYTE) NOT NULL ENABLE,
    PARTNER_REF_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6),
    ROUTING_PRIORITY NUMBER(9,0) , PRIMARY KEY (ROUTING_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_ROUTING_DEFAULT
--------------------------------------------------------
CREATE TABLE PETPE_OCR_ROUTING_DEFAULT
   (    ROUTING_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ROUTING_PRIORITY NUMBER(9,0) NOT NULL ENABLE,
    ROUTING_NAME1 VARCHAR2(100 BYTE) NOT NULL ENABLE,
    ROUTING_CONDITION1 VARCHAR2(20 BYTE) NOT NULL ENABLE,
    ROUTING_VALUE1 VARCHAR2(4000 BYTE) NOT NULL ENABLE,
    ROUTING_NAME2 VARCHAR2(100 BYTE),
    ROUTING_CONDITION2 VARCHAR2(20 BYTE),
    ROUTING_VALUE2 VARCHAR2(4000 BYTE),
    QUEUE_REF VARCHAR2(300 BYTE) NOT NULL ENABLE,
    QUEUE_REF_NAME VARCHAR2(700 BYTE) NOT NULL ENABLE,
    PARTNER_REF VARCHAR2(20 BYTE),
    PARTNER_REF_NAME VARCHAR2(100 BYTE),
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (ROUTING_ID, ROUTING_PRIORITY)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_VALIDATION_RULES
--------------------------------------------------------
CREATE TABLE PETPE_OCR_VALIDATION_RULES
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    VALIDATION_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    DESCRIPTION VARCHAR2(200 BYTE),
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6) , PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_VALIDATION_VALUES
--------------------------------------------------------
CREATE TABLE PETPE_OCR_VALIDATION_VALUES
   (    PK_ID VARCHAR2(20 BYTE) NOT NULL ENABLE,
    VALIDATION_RULE_REF VARCHAR2(20 BYTE),
    REF_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    REF_VALUE1 VARCHAR2(100 BYTE),
    REF_VALUE2 VARCHAR2(100 BYTE),
    REF_VALUE3 VARCHAR2(100 BYTE),
    CREATED_BY VARCHAR2(15 BYTE) NOT NULL ENABLE,
    CREATED_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    LAST_UPDATED_BY VARCHAR2(15 BYTE),
    LAST_UPDATED_DT TIMESTAMP (6), PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_OCR_ACTIVITY_HISTORY
--------------------------------------------------------
CREATE TABLE PETPE_OCR_ACTIVITY_HISTORY
   (    PK_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_REF_ID VARCHAR2(50 BYTE) NOT NULL ENABLE,
    PO_NUMBER VARCHAR2(30 BYTE),
    USER_NAME VARCHAR2(100 BYTE) NOT NULL ENABLE,
    USER_ID VARCHAR2(15 BYTE) NOT NULL ENABLE,
    ACTIVITY_DT TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
    ACTIVITY VARCHAR2(2000 BYTE) , PRIMARY KEY (PK_ID)
   );
