--------------------------------------------------------
--  DDL for ALL Tables --Dec-11-2019-- USER_ID, CREATED_BY, and LAST_UPDATED_BY COLUMNS length increased to 100
--------------------------------------------------------

ALTER TABLE PETPE_APP_ACTIVITY_HISTORY MODIFY USER_ID VARCHAR2(100);

ALTER TABLE PETPE_APPLICATION MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_APPLICATION MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_APPLICATION_SFG MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_APPLICATION_SFG MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_AS2 MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_AS2 MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_B2B_ACTIVITY_HISTORY MODIFY USER_ID VARCHAR2(100);

ALTER TABLE PETPE_CORRELATION_NAMES MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_CORRELATION_NAMES MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_EC MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_EC MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_FILESYSTEM MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_FILESYSTEM MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_FTP MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_FTP MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_HTTP MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_HTTP MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_MAILBOX MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_MAILBOX MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_MQ MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_MQ MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_POOLING_INTERVAL MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_POOLING_INTERVAL MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_SAP MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_SAP MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_SFG_FTP MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_SFG_FTP MODIFY LAST_UPDATED_BY VARCHAR2(100);


ALTER TABLE PETPE_SMTP MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_SMTP MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_TP_ACTIVITY_HISTORY MODIFY USER_ID VARCHAR2(100);

ALTER TABLE PETPE_TRADINGPARTNER MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_TRADINGPARTNER MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_TRADINGPARTNER_SFG MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_TRADINGPARTNER_SFG MODIFY LAST_UPDATED_BY VARCHAR2(100);

ALTER TABLE PETPE_WEBSERVICE MODIFY CREATED_BY VARCHAR2(100);

ALTER TABLE PETPE_WEBSERVICE MODIFY LAST_UPDATED_BY VARCHAR2(100);


