/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pe.pcm.sql;

import com.pe.pcm.exception.GlobalExceptionHandler;
import com.pe.pcm.pem.PemDbObjectDataTypeRepository;
import com.pe.pcm.pem.PemDbObjectRepository;
import com.pe.pcm.pem.entity.PemDbObjectDataTypeEntity;
import com.pe.pcm.pem.entity.PemDbObjectEntity;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.function.Function;
import java.util.stream.Collectors;
import java.util.stream.StreamSupport;

/**
 * @author Chenchu Kiran.
 */

@Service
public class PemDbObjectsService {

    private final PemDbObjectRepository pemDbObjectRepository;
    private final PemDbObjectDataTypeRepository pemDbObjectDataTypeRepository;

    @Autowired
    public PemDbObjectsService(PemDbObjectRepository pemDbObjectRepository, PemDbObjectDataTypeRepository pemDbObjectDataTypeRepository) {
        this.pemDbObjectRepository = pemDbObjectRepository;
        this.pemDbObjectDataTypeRepository = pemDbObjectDataTypeRepository;
    }


    public void create(PemDbObjectModel pemDbObjectModel) {
        pemDbObjectRepository.save(mapperToEntity.apply(pemDbObjectModel));
    }

    public void createDataType(PemDbObjectDataTypeModel pemDbObjectDataTypeModel) {
        pemDbObjectDataTypeRepository.save(mapperToObjectDataTypeEntity.apply(pemDbObjectDataTypeModel));
    }


    public void update(PemDbObjectModel pemDbObjectModel) {
        pemDbObjectRepository.save(mapperToEntity.apply(pemDbObjectModel));
    }

    public void delete(String seqId) {
        pemDbObjectRepository.deleteById(Integer.valueOf(seqId));
    }

    public PemDbObjectModel get(String seqId) {
        return serialize.apply(pemDbObjectRepository.findById(Integer.valueOf(seqId)).orElseThrow(() -> GlobalExceptionHandler.notFound("Record not found.")));
    }

    public List<PemDbObjectEntity> findAll() {
        return StreamSupport
                .stream(pemDbObjectRepository.findAll().spliterator(), false)
                .collect(Collectors.toList());
    }

    private static final Function<PemDbObjectEntity, PemDbObjectModel> serialize = pemDbObjectEntity ->
            new PemDbObjectModel().setSeqId(pemDbObjectEntity.getSeqId())
                    .setTableName(pemDbObjectEntity.getTableName())
                    .setDistinctColumnName(pemDbObjectEntity.getDistinctColumnName())
                    .setColumnName1(pemDbObjectEntity.getColumnName1())
                    .setColumnName2(pemDbObjectEntity.getColumnName2())
                    .setColumnName3(pemDbObjectEntity.getColumnName3())
                    .setColumnName4(pemDbObjectEntity.getColumnName4())
                    .setColumnName5(pemDbObjectEntity.getColumnName5())
                    .setColumnName6(pemDbObjectEntity.getColumnName6())
                    .setColumnName7(pemDbObjectEntity.getColumnName7())
                    .setColumnName8(pemDbObjectEntity.getColumnName8())
                    .setColumnName9(pemDbObjectEntity.getColumnName9())
                    .setColumnName10(pemDbObjectEntity.getColumnName10())
                    .setColumnName11(pemDbObjectEntity.getColumnName11())
                    .setColumnName12(pemDbObjectEntity.getColumnName12())
                    .setColumnName13(pemDbObjectEntity.getColumnName13())
                    .setColumnName14(pemDbObjectEntity.getColumnName14())
                    .setColumnName15(pemDbObjectEntity.getColumnName15())
                    .setColumnName16(pemDbObjectEntity.getColumnName16())
                    .setColumnName17(pemDbObjectEntity.getColumnName17())
                    .setColumnName18(pemDbObjectEntity.getColumnName18())
                    .setColumnName19(pemDbObjectEntity.getColumnName19())
                    .setColumnName20(pemDbObjectEntity.getColumnName20())
                    .setColumnName21(pemDbObjectEntity.getColumnName21())
                    .setColumnName22(pemDbObjectEntity.getColumnName22())
                    .setColumnName23(pemDbObjectEntity.getColumnName23())
                    .setColumnName24(pemDbObjectEntity.getColumnName24())
                    .setColumnName25(pemDbObjectEntity.getColumnName25())
                    .setColumnName26(pemDbObjectEntity.getColumnName26())
                    .setColumnName27(pemDbObjectEntity.getColumnName27())
                    .setColumnName28(pemDbObjectEntity.getColumnName28())
                    .setColumnName29(pemDbObjectEntity.getColumnName29())
                    .setColumnName30(pemDbObjectEntity.getColumnName30())
                    .setColumnName31(pemDbObjectEntity.getColumnName31())
                    .setColumnName32(pemDbObjectEntity.getColumnName32())
                    .setColumnName33(pemDbObjectEntity.getColumnName33())
                    .setColumnName34(pemDbObjectEntity.getColumnName34())
                    .setColumnName35(pemDbObjectEntity.getColumnName35())
                    .setColumnName36(pemDbObjectEntity.getColumnName36())
                    .setColumnName37(pemDbObjectEntity.getColumnName37())
                    .setColumnName38(pemDbObjectEntity.getColumnName38())
                    .setColumnName39(pemDbObjectEntity.getColumnName39())
                    .setColumnName40(pemDbObjectEntity.getColumnName40())
                    .setColumnName41(pemDbObjectEntity.getColumnName41())
                    .setColumnName42(pemDbObjectEntity.getColumnName42())
                    .setColumnName43(pemDbObjectEntity.getColumnName43())
                    .setColumnName44(pemDbObjectEntity.getColumnName44())
                    .setColumnName45(pemDbObjectEntity.getColumnName45())
                    .setColumnName46(pemDbObjectEntity.getColumnName46())
                    .setColumnName47(pemDbObjectEntity.getColumnName47())
                    .setColumnName48(pemDbObjectEntity.getColumnName48())
                    .setColumnName49(pemDbObjectEntity.getColumnName49())
                    .setColumnName50(pemDbObjectEntity.getColumnName50())
                    .setColumnName51(pemDbObjectEntity.getColumnName51())
                    .setColumnName52(pemDbObjectEntity.getColumnName52())
                    .setColumnName53(pemDbObjectEntity.getColumnName53())
                    .setColumnName54(pemDbObjectEntity.getColumnName54())
                    .setColumnName55(pemDbObjectEntity.getColumnName55())
                    .setColumnName56(pemDbObjectEntity.getColumnName56())
                    .setColumnName57(pemDbObjectEntity.getColumnName57())
                    .setColumnName58(pemDbObjectEntity.getColumnName58())
                    .setColumnName59(pemDbObjectEntity.getColumnName59())
                    .setColumnName60(pemDbObjectEntity.getColumnName60())
                    .setColumnName61(pemDbObjectEntity.getColumnName61())
                    .setColumnName62(pemDbObjectEntity.getColumnName62())
                    .setColumnName63(pemDbObjectEntity.getColumnName63())
                    .setColumnName64(pemDbObjectEntity.getColumnName64())
                    .setColumnName65(pemDbObjectEntity.getColumnName65())
                    .setColumnName66(pemDbObjectEntity.getColumnName66())
                    .setColumnName67(pemDbObjectEntity.getColumnName67())
                    .setColumnName68(pemDbObjectEntity.getColumnName68())
                    .setColumnName69(pemDbObjectEntity.getColumnName69())
                    .setColumnName70(pemDbObjectEntity.getColumnName70())
                    .setColumnName71(pemDbObjectEntity.getColumnName71())
                    .setColumnName72(pemDbObjectEntity.getColumnName72())
                    .setColumnName73(pemDbObjectEntity.getColumnName73())
                    .setColumnName74(pemDbObjectEntity.getColumnName74())
                    .setColumnName75(pemDbObjectEntity.getColumnName75())
                    .setColumnName76(pemDbObjectEntity.getColumnName76())
                    .setColumnName77(pemDbObjectEntity.getColumnName77())
                    .setColumnName78(pemDbObjectEntity.getColumnName78())
                    .setColumnName79(pemDbObjectEntity.getColumnName79())
                    .setColumnName80(pemDbObjectEntity.getColumnName80())
                    .setColumnName81(pemDbObjectEntity.getColumnName81())
                    .setColumnName82(pemDbObjectEntity.getColumnName82())
                    .setColumnName83(pemDbObjectEntity.getColumnName83())
                    .setColumnName84(pemDbObjectEntity.getColumnName84())
                    .setColumnName85(pemDbObjectEntity.getColumnName85())
                    .setColumnName86(pemDbObjectEntity.getColumnName86())
                    .setColumnName87(pemDbObjectEntity.getColumnName87())
                    .setColumnName88(pemDbObjectEntity.getColumnName88())
                    .setColumnName89(pemDbObjectEntity.getColumnName89())
                    .setColumnName90(pemDbObjectEntity.getColumnName90())
                    .setColumnName91(pemDbObjectEntity.getColumnName91())
                    .setColumnName92(pemDbObjectEntity.getColumnName92())
                    .setColumnName93(pemDbObjectEntity.getColumnName93())
                    .setColumnName94(pemDbObjectEntity.getColumnName94())
                    .setColumnName95(pemDbObjectEntity.getColumnName95())
                    .setColumnName96(pemDbObjectEntity.getColumnName96())
                    .setColumnName97(pemDbObjectEntity.getColumnName97())
                    .setColumnName98(pemDbObjectEntity.getColumnName98())
                    .setColumnName99(pemDbObjectEntity.getColumnName99())
                    .setColumnName100(pemDbObjectEntity.getColumnName100())
                    .setColumnName101(pemDbObjectEntity.getColumnName101())
                    .setColumnName102(pemDbObjectEntity.getColumnName102())
                    .setColumnName103(pemDbObjectEntity.getColumnName103())
                    .setColumnName104(pemDbObjectEntity.getColumnName104())
                    .setColumnName105(pemDbObjectEntity.getColumnName105())
                    .setColumnName106(pemDbObjectEntity.getColumnName106())
                    .setColumnName107(pemDbObjectEntity.getColumnName107())
                    .setColumnName108(pemDbObjectEntity.getColumnName108())
                    .setColumnName109(pemDbObjectEntity.getColumnName109())
                    .setColumnName110(pemDbObjectEntity.getColumnName110())
                    .setColumnName111(pemDbObjectEntity.getColumnName111())
                    .setColumnName112(pemDbObjectEntity.getColumnName112())
                    .setColumnName113(pemDbObjectEntity.getColumnName113())
                    .setColumnName114(pemDbObjectEntity.getColumnName114())
                    .setColumnName115(pemDbObjectEntity.getColumnName115())
                    .setColumnName116(pemDbObjectEntity.getColumnName116())
                    .setColumnName117(pemDbObjectEntity.getColumnName117())
                    .setColumnName118(pemDbObjectEntity.getColumnName118())
                    .setColumnName119(pemDbObjectEntity.getColumnName119())
                    .setColumnName120(pemDbObjectEntity.getColumnName120())
                    .setColumnName121(pemDbObjectEntity.getColumnName121())
                    .setColumnName122(pemDbObjectEntity.getColumnName122())
                    .setColumnName123(pemDbObjectEntity.getColumnName123())
                    .setColumnName124(pemDbObjectEntity.getColumnName124())
                    .setColumnName125(pemDbObjectEntity.getColumnName125())
                    .setColumnName126(pemDbObjectEntity.getColumnName126())
                    .setColumnName127(pemDbObjectEntity.getColumnName127())
                    .setColumnName128(pemDbObjectEntity.getColumnName128())
                    .setColumnName129(pemDbObjectEntity.getColumnName129())
                    .setColumnName130(pemDbObjectEntity.getColumnName130())
                    .setColumnName131(pemDbObjectEntity.getColumnName131())
                    .setColumnName132(pemDbObjectEntity.getColumnName132())
                    .setColumnName133(pemDbObjectEntity.getColumnName133())
                    .setColumnName134(pemDbObjectEntity.getColumnName134())
                    .setColumnName135(pemDbObjectEntity.getColumnName135())
                    .setColumnName136(pemDbObjectEntity.getColumnName136())
                    .setColumnName137(pemDbObjectEntity.getColumnName137())
                    .setColumnName138(pemDbObjectEntity.getColumnName138())
                    .setColumnName139(pemDbObjectEntity.getColumnName139())
                    .setColumnName140(pemDbObjectEntity.getColumnName140())
                    .setColumnName141(pemDbObjectEntity.getColumnName141())
                    .setColumnName142(pemDbObjectEntity.getColumnName142())
                    .setColumnName143(pemDbObjectEntity.getColumnName143())
                    .setColumnName144(pemDbObjectEntity.getColumnName144())
                    .setColumnName145(pemDbObjectEntity.getColumnName145())
                    .setColumnName146(pemDbObjectEntity.getColumnName146())
                    .setColumnName147(pemDbObjectEntity.getColumnName147())
                    .setColumnName148(pemDbObjectEntity.getColumnName148())
                    .setColumnName149(pemDbObjectEntity.getColumnName149())
                    .setColumnName150(pemDbObjectEntity.getColumnName150())
                    .setWhereColumnName1(pemDbObjectEntity.getWhereColumnName1())
                    .setWhereColumnName2(pemDbObjectEntity.getWhereColumnName2())
                    .setWhereColumnName3(pemDbObjectEntity.getWhereColumnName3())
                    .setWhereColumnName4(pemDbObjectEntity.getWhereColumnName4())
                    .setWhereColumnName5(pemDbObjectEntity.getWhereColumnName5())
                    .setWhereColumnName6(pemDbObjectEntity.getWhereColumnName6())
                    .setWhereColumnName7(pemDbObjectEntity.getWhereColumnName7())
                    .setWhereColumnName8(pemDbObjectEntity.getWhereColumnName8())
                    .setWhereColumnName9(pemDbObjectEntity.getWhereColumnName9())
                    .setWhereColumnName10(pemDbObjectEntity.getWhereColumnName10());

    private static final Function<PemDbObjectModel, PemDbObjectEntity> mapperToEntity = pemDbObjectModel ->
            new PemDbObjectEntity().setSeqId(pemDbObjectModel.getSeqId())
                    .setTableName(pemDbObjectModel.getTableName())
                    .setDistinctColumnName(pemDbObjectModel.getDistinctColumnName())
                    .setColumnName1(pemDbObjectModel.getColumnName1())
                    .setColumnName2(pemDbObjectModel.getColumnName2())
                    .setColumnName3(pemDbObjectModel.getColumnName3())
                    .setColumnName4(pemDbObjectModel.getColumnName4())
                    .setColumnName5(pemDbObjectModel.getColumnName5())
                    .setColumnName6(pemDbObjectModel.getColumnName6())
                    .setColumnName7(pemDbObjectModel.getColumnName7())
                    .setColumnName8(pemDbObjectModel.getColumnName8())
                    .setColumnName9(pemDbObjectModel.getColumnName9())
                    .setColumnName10(pemDbObjectModel.getColumnName10())
                    .setColumnName11(pemDbObjectModel.getColumnName11())
                    .setColumnName12(pemDbObjectModel.getColumnName12())
                    .setColumnName13(pemDbObjectModel.getColumnName13())
                    .setColumnName14(pemDbObjectModel.getColumnName14())
                    .setColumnName15(pemDbObjectModel.getColumnName15())
                    .setColumnName16(pemDbObjectModel.getColumnName16())
                    .setColumnName17(pemDbObjectModel.getColumnName17())
                    .setColumnName18(pemDbObjectModel.getColumnName18())
                    .setColumnName19(pemDbObjectModel.getColumnName19())
                    .setColumnName20(pemDbObjectModel.getColumnName20())
                    .setColumnName21(pemDbObjectModel.getColumnName21())
                    .setColumnName22(pemDbObjectModel.getColumnName22())
                    .setColumnName23(pemDbObjectModel.getColumnName23())
                    .setColumnName24(pemDbObjectModel.getColumnName24())
                    .setColumnName25(pemDbObjectModel.getColumnName25())
                    .setColumnName26(pemDbObjectModel.getColumnName26())
                    .setColumnName27(pemDbObjectModel.getColumnName27())
                    .setColumnName28(pemDbObjectModel.getColumnName28())
                    .setColumnName29(pemDbObjectModel.getColumnName29())
                    .setColumnName30(pemDbObjectModel.getColumnName30())
                    .setColumnName31(pemDbObjectModel.getColumnName31())
                    .setColumnName32(pemDbObjectModel.getColumnName32())
                    .setColumnName33(pemDbObjectModel.getColumnName33())
                    .setColumnName34(pemDbObjectModel.getColumnName34())
                    .setColumnName35(pemDbObjectModel.getColumnName35())
                    .setColumnName36(pemDbObjectModel.getColumnName36())
                    .setColumnName37(pemDbObjectModel.getColumnName37())
                    .setColumnName38(pemDbObjectModel.getColumnName38())
                    .setColumnName39(pemDbObjectModel.getColumnName39())
                    .setColumnName40(pemDbObjectModel.getColumnName40())
                    .setColumnName41(pemDbObjectModel.getColumnName41())
                    .setColumnName42(pemDbObjectModel.getColumnName42())
                    .setColumnName43(pemDbObjectModel.getColumnName43())
                    .setColumnName44(pemDbObjectModel.getColumnName44())
                    .setColumnName45(pemDbObjectModel.getColumnName45())
                    .setColumnName46(pemDbObjectModel.getColumnName46())
                    .setColumnName47(pemDbObjectModel.getColumnName47())
                    .setColumnName48(pemDbObjectModel.getColumnName48())
                    .setColumnName49(pemDbObjectModel.getColumnName49())
                    .setColumnName50(pemDbObjectModel.getColumnName50())
                    .setColumnName51(pemDbObjectModel.getColumnName51())
                    .setColumnName52(pemDbObjectModel.getColumnName52())
                    .setColumnName53(pemDbObjectModel.getColumnName53())
                    .setColumnName54(pemDbObjectModel.getColumnName54())
                    .setColumnName55(pemDbObjectModel.getColumnName55())
                    .setColumnName56(pemDbObjectModel.getColumnName56())
                    .setColumnName57(pemDbObjectModel.getColumnName57())
                    .setColumnName58(pemDbObjectModel.getColumnName58())
                    .setColumnName59(pemDbObjectModel.getColumnName59())
                    .setColumnName60(pemDbObjectModel.getColumnName60())
                    .setColumnName61(pemDbObjectModel.getColumnName61())
                    .setColumnName62(pemDbObjectModel.getColumnName62())
                    .setColumnName63(pemDbObjectModel.getColumnName63())
                    .setColumnName64(pemDbObjectModel.getColumnName64())
                    .setColumnName65(pemDbObjectModel.getColumnName65())
                    .setColumnName66(pemDbObjectModel.getColumnName66())
                    .setColumnName67(pemDbObjectModel.getColumnName67())
                    .setColumnName68(pemDbObjectModel.getColumnName68())
                    .setColumnName69(pemDbObjectModel.getColumnName69())
                    .setColumnName70(pemDbObjectModel.getColumnName70())
                    .setColumnName71(pemDbObjectModel.getColumnName71())
                    .setColumnName72(pemDbObjectModel.getColumnName72())
                    .setColumnName73(pemDbObjectModel.getColumnName73())
                    .setColumnName74(pemDbObjectModel.getColumnName74())
                    .setColumnName75(pemDbObjectModel.getColumnName75())
                    .setColumnName76(pemDbObjectModel.getColumnName76())
                    .setColumnName77(pemDbObjectModel.getColumnName77())
                    .setColumnName78(pemDbObjectModel.getColumnName78())
                    .setColumnName79(pemDbObjectModel.getColumnName79())
                    .setColumnName80(pemDbObjectModel.getColumnName80())
                    .setColumnName81(pemDbObjectModel.getColumnName81())
                    .setColumnName82(pemDbObjectModel.getColumnName82())
                    .setColumnName83(pemDbObjectModel.getColumnName83())
                    .setColumnName84(pemDbObjectModel.getColumnName84())
                    .setColumnName85(pemDbObjectModel.getColumnName85())
                    .setColumnName86(pemDbObjectModel.getColumnName86())
                    .setColumnName87(pemDbObjectModel.getColumnName87())
                    .setColumnName88(pemDbObjectModel.getColumnName88())
                    .setColumnName89(pemDbObjectModel.getColumnName89())
                    .setColumnName90(pemDbObjectModel.getColumnName90())
                    .setColumnName91(pemDbObjectModel.getColumnName91())
                    .setColumnName92(pemDbObjectModel.getColumnName92())
                    .setColumnName93(pemDbObjectModel.getColumnName93())
                    .setColumnName94(pemDbObjectModel.getColumnName94())
                    .setColumnName95(pemDbObjectModel.getColumnName95())
                    .setColumnName96(pemDbObjectModel.getColumnName96())
                    .setColumnName97(pemDbObjectModel.getColumnName97())
                    .setColumnName98(pemDbObjectModel.getColumnName98())
                    .setColumnName99(pemDbObjectModel.getColumnName99())
                    .setColumnName100(pemDbObjectModel.getColumnName100())
                    .setColumnName101(pemDbObjectModel.getColumnName101())
                    .setColumnName102(pemDbObjectModel.getColumnName102())
                    .setColumnName103(pemDbObjectModel.getColumnName103())
                    .setColumnName104(pemDbObjectModel.getColumnName104())
                    .setColumnName105(pemDbObjectModel.getColumnName105())
                    .setColumnName106(pemDbObjectModel.getColumnName106())
                    .setColumnName107(pemDbObjectModel.getColumnName107())
                    .setColumnName108(pemDbObjectModel.getColumnName108())
                    .setColumnName109(pemDbObjectModel.getColumnName109())
                    .setColumnName110(pemDbObjectModel.getColumnName110())
                    .setColumnName111(pemDbObjectModel.getColumnName111())
                    .setColumnName112(pemDbObjectModel.getColumnName112())
                    .setColumnName113(pemDbObjectModel.getColumnName113())
                    .setColumnName114(pemDbObjectModel.getColumnName114())
                    .setColumnName115(pemDbObjectModel.getColumnName115())
                    .setColumnName116(pemDbObjectModel.getColumnName116())
                    .setColumnName117(pemDbObjectModel.getColumnName117())
                    .setColumnName118(pemDbObjectModel.getColumnName118())
                    .setColumnName119(pemDbObjectModel.getColumnName119())
                    .setColumnName120(pemDbObjectModel.getColumnName120())
                    .setColumnName121(pemDbObjectModel.getColumnName121())
                    .setColumnName122(pemDbObjectModel.getColumnName122())
                    .setColumnName123(pemDbObjectModel.getColumnName123())
                    .setColumnName124(pemDbObjectModel.getColumnName124())
                    .setColumnName125(pemDbObjectModel.getColumnName125())
                    .setColumnName126(pemDbObjectModel.getColumnName126())
                    .setColumnName127(pemDbObjectModel.getColumnName127())
                    .setColumnName128(pemDbObjectModel.getColumnName128())
                    .setColumnName129(pemDbObjectModel.getColumnName129())
                    .setColumnName130(pemDbObjectModel.getColumnName130())
                    .setColumnName131(pemDbObjectModel.getColumnName131())
                    .setColumnName132(pemDbObjectModel.getColumnName132())
                    .setColumnName133(pemDbObjectModel.getColumnName133())
                    .setColumnName134(pemDbObjectModel.getColumnName134())
                    .setColumnName135(pemDbObjectModel.getColumnName135())
                    .setColumnName136(pemDbObjectModel.getColumnName136())
                    .setColumnName137(pemDbObjectModel.getColumnName137())
                    .setColumnName138(pemDbObjectModel.getColumnName138())
                    .setColumnName139(pemDbObjectModel.getColumnName139())
                    .setColumnName140(pemDbObjectModel.getColumnName140())
                    .setColumnName141(pemDbObjectModel.getColumnName141())
                    .setColumnName142(pemDbObjectModel.getColumnName142())
                    .setColumnName143(pemDbObjectModel.getColumnName143())
                    .setColumnName144(pemDbObjectModel.getColumnName144())
                    .setColumnName145(pemDbObjectModel.getColumnName145())
                    .setColumnName146(pemDbObjectModel.getColumnName146())
                    .setColumnName147(pemDbObjectModel.getColumnName147())
                    .setColumnName148(pemDbObjectModel.getColumnName148())
                    .setColumnName149(pemDbObjectModel.getColumnName149())
                    .setColumnName150(pemDbObjectModel.getColumnName150())
                    .setWhereColumnName1(pemDbObjectModel.getWhereColumnName1())
                    .setWhereColumnName2(pemDbObjectModel.getWhereColumnName2())
                    .setWhereColumnName3(pemDbObjectModel.getWhereColumnName3())
                    .setWhereColumnName4(pemDbObjectModel.getWhereColumnName4())
                    .setWhereColumnName5(pemDbObjectModel.getWhereColumnName5())
                    .setWhereColumnName6(pemDbObjectModel.getWhereColumnName6())
                    .setWhereColumnName7(pemDbObjectModel.getWhereColumnName7())
                    .setWhereColumnName8(pemDbObjectModel.getWhereColumnName8())
                    .setWhereColumnName9(pemDbObjectModel.getWhereColumnName9())
                    .setWhereColumnName10(pemDbObjectModel.getWhereColumnName10());

    private static final Function<PemDbObjectDataTypeModel, PemDbObjectDataTypeEntity> mapperToObjectDataTypeEntity = pemDbObjectDataTypeModel ->
            new PemDbObjectDataTypeEntity().setSeqId(pemDbObjectDataTypeModel.getSeqId())
                    .setColumnName1Datatype(pemDbObjectDataTypeModel.getColumnName1Datatype())
                    .setColumnName2Datatype(pemDbObjectDataTypeModel.getColumnName2Datatype())
                    .setColumnName3Datatype(pemDbObjectDataTypeModel.getColumnName3Datatype())
                    .setColumnName4Datatype(pemDbObjectDataTypeModel.getColumnName4Datatype())
                    .setColumnName5Datatype(pemDbObjectDataTypeModel.getColumnName5Datatype())
                    .setColumnName6Datatype(pemDbObjectDataTypeModel.getColumnName6Datatype())
                    .setColumnName7Datatype(pemDbObjectDataTypeModel.getColumnName7Datatype())
                    .setColumnName8Datatype(pemDbObjectDataTypeModel.getColumnName8Datatype())
                    .setColumnName9Datatype(pemDbObjectDataTypeModel.getColumnName9Datatype())
                    .setColumnName10Datatype(pemDbObjectDataTypeModel.getColumnName10Datatype())
                    .setColumnName11Datatype(pemDbObjectDataTypeModel.getColumnName11Datatype())
                    .setColumnName12Datatype(pemDbObjectDataTypeModel.getColumnName12Datatype())
                    .setColumnName13Datatype(pemDbObjectDataTypeModel.getColumnName13Datatype())
                    .setColumnName14Datatype(pemDbObjectDataTypeModel.getColumnName14Datatype())
                    .setColumnName15Datatype(pemDbObjectDataTypeModel.getColumnName15Datatype())
                    .setColumnName16Datatype(pemDbObjectDataTypeModel.getColumnName16Datatype())
                    .setColumnName17Datatype(pemDbObjectDataTypeModel.getColumnName17Datatype())
                    .setColumnName18Datatype(pemDbObjectDataTypeModel.getColumnName18Datatype())
                    .setColumnName19Datatype(pemDbObjectDataTypeModel.getColumnName19Datatype())
                    .setColumnName20Datatype(pemDbObjectDataTypeModel.getColumnName20Datatype())
                    .setColumnName21Datatype(pemDbObjectDataTypeModel.getColumnName21Datatype())
                    .setColumnName22Datatype(pemDbObjectDataTypeModel.getColumnName22Datatype())
                    .setColumnName23Datatype(pemDbObjectDataTypeModel.getColumnName23Datatype())
                    .setColumnName24Datatype(pemDbObjectDataTypeModel.getColumnName24Datatype())
                    .setColumnName25Datatype(pemDbObjectDataTypeModel.getColumnName25Datatype())
                    .setColumnName26Datatype(pemDbObjectDataTypeModel.getColumnName26Datatype())
                    .setColumnName27Datatype(pemDbObjectDataTypeModel.getColumnName27Datatype())
                    .setColumnName28Datatype(pemDbObjectDataTypeModel.getColumnName28Datatype())
                    .setColumnName29Datatype(pemDbObjectDataTypeModel.getColumnName29Datatype())
                    .setColumnName30Datatype(pemDbObjectDataTypeModel.getColumnName30Datatype())
                    .setColumnName31Datatype(pemDbObjectDataTypeModel.getColumnName31Datatype())
                    .setColumnName32Datatype(pemDbObjectDataTypeModel.getColumnName32Datatype())
                    .setColumnName33Datatype(pemDbObjectDataTypeModel.getColumnName33Datatype())
                    .setColumnName34Datatype(pemDbObjectDataTypeModel.getColumnName34Datatype())
                    .setColumnName35Datatype(pemDbObjectDataTypeModel.getColumnName35Datatype())
                    .setColumnName36Datatype(pemDbObjectDataTypeModel.getColumnName36Datatype())
                    .setColumnName37Datatype(pemDbObjectDataTypeModel.getColumnName37Datatype())
                    .setColumnName38Datatype(pemDbObjectDataTypeModel.getColumnName38Datatype())
                    .setColumnName39Datatype(pemDbObjectDataTypeModel.getColumnName39Datatype())
                    .setColumnName40Datatype(pemDbObjectDataTypeModel.getColumnName40Datatype())
                    .setColumnName41Datatype(pemDbObjectDataTypeModel.getColumnName41Datatype())
                    .setColumnName42Datatype(pemDbObjectDataTypeModel.getColumnName42Datatype())
                    .setColumnName43Datatype(pemDbObjectDataTypeModel.getColumnName43Datatype())
                    .setColumnName44Datatype(pemDbObjectDataTypeModel.getColumnName44Datatype())
                    .setColumnName45Datatype(pemDbObjectDataTypeModel.getColumnName45Datatype())
                    .setColumnName46Datatype(pemDbObjectDataTypeModel.getColumnName46Datatype())
                    .setColumnName47Datatype(pemDbObjectDataTypeModel.getColumnName47Datatype())
                    .setColumnName48Datatype(pemDbObjectDataTypeModel.getColumnName48Datatype())
                    .setColumnName49Datatype(pemDbObjectDataTypeModel.getColumnName49Datatype())
                    .setColumnName50Datatype(pemDbObjectDataTypeModel.getColumnName50Datatype())
                    .setColumnName51Datatype(pemDbObjectDataTypeModel.getColumnName51Datatype())
                    .setColumnName52Datatype(pemDbObjectDataTypeModel.getColumnName52Datatype())
                    .setColumnName53Datatype(pemDbObjectDataTypeModel.getColumnName53Datatype())
                    .setColumnName54Datatype(pemDbObjectDataTypeModel.getColumnName54Datatype())
                    .setColumnName55Datatype(pemDbObjectDataTypeModel.getColumnName55Datatype())
                    .setColumnName56Datatype(pemDbObjectDataTypeModel.getColumnName56Datatype())
                    .setColumnName57Datatype(pemDbObjectDataTypeModel.getColumnName57Datatype())
                    .setColumnName58Datatype(pemDbObjectDataTypeModel.getColumnName58Datatype())
                    .setColumnName59Datatype(pemDbObjectDataTypeModel.getColumnName59Datatype())
                    .setColumnName60Datatype(pemDbObjectDataTypeModel.getColumnName60Datatype())
                    .setColumnName61Datatype(pemDbObjectDataTypeModel.getColumnName61Datatype())
                    .setColumnName62Datatype(pemDbObjectDataTypeModel.getColumnName62Datatype())
                    .setColumnName63Datatype(pemDbObjectDataTypeModel.getColumnName63Datatype())
                    .setColumnName64Datatype(pemDbObjectDataTypeModel.getColumnName64Datatype())
                    .setColumnName65Datatype(pemDbObjectDataTypeModel.getColumnName65Datatype())
                    .setColumnName66Datatype(pemDbObjectDataTypeModel.getColumnName66Datatype())
                    .setColumnName67Datatype(pemDbObjectDataTypeModel.getColumnName67Datatype())
                    .setColumnName68Datatype(pemDbObjectDataTypeModel.getColumnName68Datatype())
                    .setColumnName69Datatype(pemDbObjectDataTypeModel.getColumnName69Datatype())
                    .setColumnName70Datatype(pemDbObjectDataTypeModel.getColumnName70Datatype())
                    .setColumnName71Datatype(pemDbObjectDataTypeModel.getColumnName71Datatype())
                    .setColumnName72Datatype(pemDbObjectDataTypeModel.getColumnName72Datatype())
                    .setColumnName73Datatype(pemDbObjectDataTypeModel.getColumnName73Datatype())
                    .setColumnName74Datatype(pemDbObjectDataTypeModel.getColumnName74Datatype())
                    .setColumnName75Datatype(pemDbObjectDataTypeModel.getColumnName75Datatype())
                    .setColumnName76Datatype(pemDbObjectDataTypeModel.getColumnName76Datatype())
                    .setColumnName77Datatype(pemDbObjectDataTypeModel.getColumnName77Datatype())
                    .setColumnName78Datatype(pemDbObjectDataTypeModel.getColumnName78Datatype())
                    .setColumnName79Datatype(pemDbObjectDataTypeModel.getColumnName79Datatype())
                    .setColumnName80Datatype(pemDbObjectDataTypeModel.getColumnName80Datatype())
                    .setColumnName81Datatype(pemDbObjectDataTypeModel.getColumnName81Datatype())
                    .setColumnName82Datatype(pemDbObjectDataTypeModel.getColumnName82Datatype())
                    .setColumnName83Datatype(pemDbObjectDataTypeModel.getColumnName83Datatype())
                    .setColumnName84Datatype(pemDbObjectDataTypeModel.getColumnName84Datatype())
                    .setColumnName85Datatype(pemDbObjectDataTypeModel.getColumnName85Datatype())
                    .setColumnName86Datatype(pemDbObjectDataTypeModel.getColumnName86Datatype())
                    .setColumnName87Datatype(pemDbObjectDataTypeModel.getColumnName87Datatype())
                    .setColumnName88Datatype(pemDbObjectDataTypeModel.getColumnName88Datatype())
                    .setColumnName89Datatype(pemDbObjectDataTypeModel.getColumnName89Datatype())
                    .setColumnName90Datatype(pemDbObjectDataTypeModel.getColumnName90Datatype())
                    .setColumnName91Datatype(pemDbObjectDataTypeModel.getColumnName91Datatype())
                    .setColumnName92Datatype(pemDbObjectDataTypeModel.getColumnName92Datatype())
                    .setColumnName93Datatype(pemDbObjectDataTypeModel.getColumnName93Datatype())
                    .setColumnName94Datatype(pemDbObjectDataTypeModel.getColumnName94Datatype())
                    .setColumnName95Datatype(pemDbObjectDataTypeModel.getColumnName95Datatype())
                    .setColumnName96Datatype(pemDbObjectDataTypeModel.getColumnName96Datatype())
                    .setColumnName97Datatype(pemDbObjectDataTypeModel.getColumnName97Datatype())
                    .setColumnName98Datatype(pemDbObjectDataTypeModel.getColumnName98Datatype())
                    .setColumnName99Datatype(pemDbObjectDataTypeModel.getColumnName99Datatype())
                    .setColumnName100Datatype(pemDbObjectDataTypeModel.getColumnName100Datatype())
                    .setColumnName101Datatype(pemDbObjectDataTypeModel.getColumnName101Datatype())
                    .setColumnName102Datatype(pemDbObjectDataTypeModel.getColumnName102Datatype())
                    .setColumnName103Datatype(pemDbObjectDataTypeModel.getColumnName103Datatype())
                    .setColumnName104Datatype(pemDbObjectDataTypeModel.getColumnName104Datatype())
                    .setColumnName105Datatype(pemDbObjectDataTypeModel.getColumnName105Datatype())
                    .setColumnName106Datatype(pemDbObjectDataTypeModel.getColumnName106Datatype())
                    .setColumnName107Datatype(pemDbObjectDataTypeModel.getColumnName107Datatype())
                    .setColumnName108Datatype(pemDbObjectDataTypeModel.getColumnName108Datatype())
                    .setColumnName109Datatype(pemDbObjectDataTypeModel.getColumnName109Datatype())
                    .setColumnName110Datatype(pemDbObjectDataTypeModel.getColumnName110Datatype())
                    .setColumnName111Datatype(pemDbObjectDataTypeModel.getColumnName101Datatype())
                    .setColumnName112Datatype(pemDbObjectDataTypeModel.getColumnName102Datatype())
                    .setColumnName113Datatype(pemDbObjectDataTypeModel.getColumnName103Datatype())
                    .setColumnName114Datatype(pemDbObjectDataTypeModel.getColumnName104Datatype())
                    .setColumnName115Datatype(pemDbObjectDataTypeModel.getColumnName105Datatype())
                    .setColumnName116Datatype(pemDbObjectDataTypeModel.getColumnName106Datatype())
                    .setColumnName117Datatype(pemDbObjectDataTypeModel.getColumnName107Datatype())
                    .setColumnName118Datatype(pemDbObjectDataTypeModel.getColumnName108Datatype())
                    .setColumnName119Datatype(pemDbObjectDataTypeModel.getColumnName109Datatype())
                    .setColumnName120Datatype(pemDbObjectDataTypeModel.getColumnName100Datatype())
                    .setColumnName121Datatype(pemDbObjectDataTypeModel.getColumnName101Datatype())
                    .setColumnName122Datatype(pemDbObjectDataTypeModel.getColumnName102Datatype())
                    .setColumnName123Datatype(pemDbObjectDataTypeModel.getColumnName103Datatype())
                    .setColumnName124Datatype(pemDbObjectDataTypeModel.getColumnName104Datatype())
                    .setColumnName125Datatype(pemDbObjectDataTypeModel.getColumnName105Datatype())
                    .setColumnName126Datatype(pemDbObjectDataTypeModel.getColumnName106Datatype())
                    .setColumnName127Datatype(pemDbObjectDataTypeModel.getColumnName107Datatype())
                    .setColumnName128Datatype(pemDbObjectDataTypeModel.getColumnName108Datatype())
                    .setColumnName129Datatype(pemDbObjectDataTypeModel.getColumnName109Datatype())
                    .setColumnName130Datatype(pemDbObjectDataTypeModel.getColumnName100Datatype())
                    .setColumnName131Datatype(pemDbObjectDataTypeModel.getColumnName101Datatype())
                    .setColumnName132Datatype(pemDbObjectDataTypeModel.getColumnName102Datatype())
                    .setColumnName133Datatype(pemDbObjectDataTypeModel.getColumnName103Datatype())
                    .setColumnName134Datatype(pemDbObjectDataTypeModel.getColumnName104Datatype())
                    .setColumnName135Datatype(pemDbObjectDataTypeModel.getColumnName105Datatype())
                    .setColumnName136Datatype(pemDbObjectDataTypeModel.getColumnName106Datatype())
                    .setColumnName137Datatype(pemDbObjectDataTypeModel.getColumnName107Datatype())
                    .setColumnName138Datatype(pemDbObjectDataTypeModel.getColumnName108Datatype())
                    .setColumnName139Datatype(pemDbObjectDataTypeModel.getColumnName109Datatype())
                    .setColumnName140Datatype(pemDbObjectDataTypeModel.getColumnName100Datatype())
                    .setColumnName141Datatype(pemDbObjectDataTypeModel.getColumnName101Datatype())
                    .setColumnName142Datatype(pemDbObjectDataTypeModel.getColumnName102Datatype())
                    .setColumnName143Datatype(pemDbObjectDataTypeModel.getColumnName103Datatype())
                    .setColumnName144Datatype(pemDbObjectDataTypeModel.getColumnName104Datatype())
                    .setColumnName145Datatype(pemDbObjectDataTypeModel.getColumnName105Datatype())
                    .setColumnName146Datatype(pemDbObjectDataTypeModel.getColumnName106Datatype())
                    .setColumnName147Datatype(pemDbObjectDataTypeModel.getColumnName107Datatype())
                    .setColumnName148Datatype(pemDbObjectDataTypeModel.getColumnName108Datatype())
                    .setColumnName149Datatype(pemDbObjectDataTypeModel.getColumnName109Datatype())
                    .setColumnName150Datatype(pemDbObjectDataTypeModel.getColumnName150Datatype())
                    .setWhereColumnName1_datatype(pemDbObjectDataTypeModel.getWhereColumnName1_datatype())
                    .setWhereColumnName2_datatype(pemDbObjectDataTypeModel.getWhereColumnName2_datatype())
                    .setWhereColumnName3_datatype(pemDbObjectDataTypeModel.getWhereColumnName3_datatype())
                    .setWhereColumnName4_datatype(pemDbObjectDataTypeModel.getWhereColumnName4_datatype())
                    .setWhereColumnName5_datatype(pemDbObjectDataTypeModel.getWhereColumnName5_datatype())
                    .setWhereColumnName6_datatype(pemDbObjectDataTypeModel.getWhereColumnName6_datatype())
                    .setWhereColumnName7_datatype(pemDbObjectDataTypeModel.getWhereColumnName7_datatype())
                    .setWhereColumnName8_datatype(pemDbObjectDataTypeModel.getWhereColumnName8_datatype())
                    .setWhereColumnName9_datatype(pemDbObjectDataTypeModel.getWhereColumnName9_datatype())
                    .setWhereColumnName10_datatype(pemDbObjectDataTypeModel.getWhereColumnName10_datatype());
}
