--------------------------------------------------------
--  DDL for Table PETPE_POOLING_INTERVAL
--------------------------------------------------------
CREATE TABLE PETPE_POOLING_INTERVAL
   ( PK_ID VARCHAR(50) NOT NULL,
    INTERVAL VARCHAR(50) NOT NULL,
    SEQ FLOAT NOT NULL ,
    DESCRIPTION VARCHAR(255),
    CREATED_BY VARCHAR(15) NOT NULL,
    LAST_UPDATED_BY VARCHAR(15),
    LAST_UPDATED_DT DATETIME2 (6),
    UNIQUE (SEQ),
    PRIMARY KEY (PK_ID)
   );

--------------------------------------------------------
--  DDL for Table PETPE_CORRELATION_NAMES
--------------------------------------------------------
CREATE TABLE PETPE_CORRELATION_NAMES
   (    PK_ID VARCHAR(20) NOT NULL,
    CORRELATION_NAME_1 VARCHAR(200),
    CORRELATION_NAME_2 VARCHAR(200),
    CORRELATION_NAME_3 VARCHAR(200),
    CORRELATION_NAME_4 VARCHAR(200),
    CORRELATION_NAME_5 VARCHAR(200),
    CORRELATION_NAME_6 VARCHAR(200),
    CORRELATION_NAME_7 VARCHAR(200),
    CORRELATION_NAME_8 VARCHAR(200),
    CORRELATION_NAME_9 VARCHAR(200),
    CORRELATION_NAME_10 VARCHAR(200) ,
	CORRELATION_NAME_11 VARCHAR(200),
	CORRELATION_NAME_12 VARCHAR(200),
	CORRELATION_NAME_13 VARCHAR(200),
	CORRELATION_NAME_14 VARCHAR(200),
	CORRELATION_NAME_15 VARCHAR(200),
	CORRELATION_NAME_16 VARCHAR(200),
	CORRELATION_NAME_17 VARCHAR(200),
	CORRELATION_NAME_18 VARCHAR(200),
	CORRELATION_NAME_19 VARCHAR(200),
	CORRELATION_NAME_20 VARCHAR(200),
	CORRELATION_NAME_21 VARCHAR(200),
	CORRELATION_NAME_22 VARCHAR(200),
	CORRELATION_NAME_23 VARCHAR(200),
	CORRELATION_NAME_24 VARCHAR(200),
	CORRELATION_NAME_25 VARCHAR(200),
	CREATED_BY VARCHAR(15),
    LAST_UPDATED_BY VARCHAR(15),
    LAST_UPDATED_DT DATETIME2 (6) , PRIMARY KEY (PK_ID)
	);
