--------------------------------------------------------
--  DDL STATEMENT
--------------------------------------------------------
ALTER TABLE PETPE_TRANSFERINFO DROP COLUMN FUNCTIONAL_ACK_DATE, FUNCTIONAL_ACK_TIME;

sp_rename 'PETPE_TRANSFERINFO.ISA_CONTROL_NUMBER', 'ISA_CTL', 'COLUMN';
sp_rename 'PETPE_TRANSFERINFO.GS_CONTROL_NUMBER', 'GS_CTL', 'COLUMN';
sp_rename 'PETPE_TRANSFERINFO.ST_CONTROL_NUMBER', 'ST_CTL', 'COLUMN';
sp_rename 'PETPE_TRANSFERINFO.FUNCTIONAL_ACK_REQUEST', 'FA_REQ', 'COLUMN';
sp_rename 'PETPE_TRANSFERINFO.SEGMENT_COUNT', 'SEG_CNT', 'COLUMN';
sp_rename 'PETPE_TRANSFERINFO.IDOC_NUMBER', 'APP_TRAN_NUM', 'COLUMN';
sp_rename 'PETPE_TRANSFERINFO.SAP_FA', 'APP_FA', 'COLUMN';
sp_rename 'PETPE_TRANSFERINFO.CHAR_CNT', 'SRC_CHAR_CNT', 'COLUMN';

ALTER TABLE PETPE_TRANSFERINFO
  ADD FA_DTM DATETIME2(6),
    APP_FA_STUS VARCHAR(15),
	APP_FA_DTM VARCHAR(15),
	DST_CHAR_CNT VARCHAR(20),
	DST_PROCL_CNT VARCHAR(20),
	BU_DIVNAME VARCHAR(20),
	TP_REF_ID VARCHAR(50),
	DLE_DTM DATETIME2(6);

CREATE INDEX FA_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (FA_DTM);
CREATE INDEX DLE_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (DLE_DTM);
