--------------------------------------------------------
--  DDL STATEMENT
--------------------------------------------------------
DROP INDEX FA_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO;
DROP INDEX DLE_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO;

ALTER TABLE PETPE_TRANSFERINFO DROP COLUMN FA_DTM, DLE_DTM;

ALTER TABLE PETPE_TRANSFERINFO
  ADD FA_DTM VARCHAR(15),
	DLE_DTM VARCHAR(15);

CREATE INDEX FA_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (FA_DTM);
CREATE INDEX DLE_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (DLE_DTM);
