--------------------------------------------------------
--  DDL STATEMENTS
--------------------------------------------------------

ALTER TABLE PETPE_CORRELATION_NAMES
  ADD CORRELATION_NAME_26 VARCHAR(200),
    CORRELATION_NAME_27 VARCHAR(200),
    CORRELATION_NAME_28 VARCHAR(200),
    CORRELATION_NAME_29 VARCHAR(200),
    CORRELATION_NAME_30 VARCHAR(200),
    CORRELATION_NAME_31 VARCHAR(200),
    CORRELATION_NAME_32 VARCHAR(200),
    CORRELATION_NAME_33 VARCHAR(200),
    CORRELATION_NAME_34 VARCHAR(200),
    CORRELATION_NAME_35 VARCHAR(200),
    CORRELATION_NAME_36 VARCHAR(200),
    CORRELATION_NAME_37 VARCHAR(200),
    CORRELATION_NAME_38 VARCHAR(200),
    CORRELATION_NAME_39 VARCHAR(200),
    CORRELATION_NAME_40 VARCHAR(200),
    CORRELATION_NAME_41 VARCHAR(200),
    CORRELATION_NAME_42 VARCHAR(200),
    CORRELATION_NAME_43 VARCHAR(200),
    CORRELATION_NAME_44 VARCHAR(200),
    CORRELATION_NAME_45 VARCHAR(200),
    CORRELATION_NAME_46 VARCHAR(200),
    CORRELATION_NAME_47 VARCHAR(200),
    CORRELATION_NAME_48 VARCHAR(200),
    CORRELATION_NAME_49 VARCHAR(200),
    CORRELATION_NAME_50 VARCHAR(200);

 ALTER TABLE PETPE_TRANSFERINFO
  ADD CORRELATION_VALUE_26 VARCHAR(max),
    CORRELATION_VALUE_27 VARCHAR(max),
    CORRELATION_VALUE_28 VARCHAR(max),
    CORRELATION_VALUE_29 VARCHAR(max),
    CORRELATION_VALUE_30 VARCHAR(max),
    CORRELATION_VALUE_31 VARCHAR(max),
    CORRELATION_VALUE_32 VARCHAR(max),
    CORRELATION_VALUE_33 VARCHAR(max),
    CORRELATION_VALUE_34 VARCHAR(max),
    CORRELATION_VALUE_35 VARCHAR(max),
    CORRELATION_VALUE_36 VARCHAR(max),
    CORRELATION_VALUE_37 VARCHAR(max),
    CORRELATION_VALUE_38 VARCHAR(max),
    CORRELATION_VALUE_39 VARCHAR(max),
    CORRELATION_VALUE_40 VARCHAR(max),
    CORRELATION_VALUE_41 VARCHAR(max),
    CORRELATION_VALUE_42 VARCHAR(max),
    CORRELATION_VALUE_43 VARCHAR(max),
    CORRELATION_VALUE_44 VARCHAR(max),
    CORRELATION_VALUE_45 VARCHAR(max),
    CORRELATION_VALUE_46 VARCHAR(max),
    CORRELATION_VALUE_47 VARCHAR(max),
    CORRELATION_VALUE_48 VARCHAR(max),
    CORRELATION_VALUE_49 VARCHAR(max),
    CORRELATION_VALUE_50 VARCHAR(max);

 ALTER TABLE PETPE_TRANSFERINFO
  ADD ISA_CONTROL_NUMBER VARCHAR(15),
       GS_CONTROL_NUMBER VARCHAR(15),
       ST_CONTROL_NUMBER VARCHAR(15),
       FUNCTIONAL_ACK_DATE VARCHAR(15),
       FUNCTIONAL_ACK_TIME VARCHAR(6),
       FUNCTIONAL_ACK_REQUEST VARCHAR(1),
       SEGMENT_COUNT VARCHAR(9),
       IDOC_NUMBER VARCHAR(15),
       SAP_FA VARCHAR(15),
       XREF_NAME VARCHAR(30),
       XREF_LOOKUP VARCHAR(15);

ALTER TABLE PETPE_MQ ADD PORT VARCHAR(30);
