--------------------------------------------------------
--  DDL OPERATIONS
--------------------------------------------------------

ALTER TABLE PETPE_TRADINGPARTNER ADD PEM_IDENTIFIER VARCHAR(255);
ALTER TABLE PETPE_APPLICATION ADD PEM_IDENTIFIER VARCHAR(255);
ALTER TABLE PETPE_PROCESSDOCS ALTER COLUMN DOCTYPE VARCHAR(255);
