--------------------------------------------------------
--  DML for Table PETPE_SO_USERS
--------------------------------------------------------
UPDATE PETPE_SO_USERS SET ROLE = 'super_admin' WHERE ROLE = 'admin';
UPDATE PETPE_SO_USERS SET ROLE = 'data_processor' WHERE ROLE = 'user';
UPDATE PETPE_SO_USERS SET ROLE = 'super_admin' WHERE ROLE = 'SUPER_ADMIN';
UPDATE PETPE_SO_USERS SET ROLE = 'admin' WHERE ROLE = 'ADMIN';
UPDATE PETPE_SO_USERS SET ROLE = 'on_boarder' WHERE ROLE = 'ON_BOARDER';
UPDATE PETPE_SO_USERS SET ROLE = 'business_admin' WHERE ROLE = 'BUSINESS_ADMIN';
UPDATE PETPE_SO_USERS SET ROLE = 'business_user' WHERE ROLE = 'BUSINESS_USER';
UPDATE PETPE_SO_USERS SET ROLE = 'data_processor' WHERE ROLE = 'DATA_PROCESSOR';
UPDATE PETPE_SO_USERS SET ROLE = 'data_processor_restricted' WHERE ROLE = 'DATA_PROCESSOR_RESTRICTED';

--------------------------------------------------------
--  DDL for PETPE_TRADINGPARTNER
--------------------------------------------------------
ALTER TABLE PETPE_TRADINGPARTNER ADD CUSTOM_TP_NAME VARCHAR(255);
ALTER TABLE PETPE_TRADINGPARTNER ADD PGP_INFO VARCHAR(255);
ALTER TABLE PETPE_TRADINGPARTNER ADD IP_WHITELIST VARCHAR(255);
ALTER TABLE PETPE_TRADINGPARTNER ADD IS_ONLY_PCM VARCHAR(1);

--------------------------------------------------------
--  DDL for PETPE_SO_USERS
--------------------------------------------------------
ALTER TABLE PETPE_SO_USERS ADD OTP VARCHAR(6);

--------------------------------------------------------
--  DDL for PETPE_CD
--------------------------------------------------------
--ALTER TABLE PETPE_CD ADD OPERATING_SYSTEM VARCHAR(20);
--ALTER TABLE PETPE_CD ADD HOST_NAME VARCHAR(255);
--ALTER TABLE PETPE_CD ADD PORT VARCHAR(10 BYTE);
--ALTER TABLE PETPE_CD ADD COPY_SIS_OPTS VARCHAR(255);
--ALTER TABLE PETPE_CD ADD CHECK_POINT VARCHAR(10);
--ALTER TABLE PETPE_CD ADD COMPRESSION_LEVEL VARCHAR(2);
--ALTER TABLE PETPE_CD ADD DISPOSITION VARCHAR(10);
--ALTER TABLE PETPE_CD ADD SUBMIT VARCHAR(255);
--ALTER TABLE PETPE_CD ADD SECURE VARCHAR(1);
--ALTER TABLE PETPE_CD ADD RUN_JOB VARCHAR(255);
--ALTER TABLE PETPE_CD ADD RUN_TASK VARCHAR(255);
--ALTER TABLE PETPE_CD ADD CA_CERTIFICATE VARCHAR(255);
--ALTER TABLE PETPE_CD ADD CIPHER_SUITS VARCHAR(2000);
--ALTER TABLE PETPE_CD ADD DCB_PARAM VARCHAR(255);
--ALTER TABLE PETPE_CD ADD DNS_NAME VARCHAR(255);
--ALTER TABLE PETPE_CD ADD UNIT VARCHAR(255);
--ALTER TABLE PETPE_CD ADD STORAGE_CLASS VARCHAR(255);
--ALTER TABLE PETPE_CD ADD SPACE VARCHAR(255);

--------------------------------------------------------
--  DDL for PETPE_AWS_S3
--------------------------------------------------------
CREATE TABLE PETPE_AWS_S3
    ( PK_ID VARCHAR(20) NOT NULL,
      SUBSCRIBER_TYPE VARCHAR(5) NOT NULL,
      SUBSCRIBER_ID VARCHAR(20) NOT NULL,
      SOURCE_PATH VARCHAR(255),
      BUCKET_NAME VARCHAR(255) NOT NULL,
      FILE_NAME VARCHAR(255),
      ACCESS_KEY VARCHAR(255) NOT NULL,
      SECRET_KEY VARCHAR(255) NOT NULL,
      ENDPOINT VARCHAR(255),
      REGION VARCHAR(255),
      ADAPTER_NAME VARCHAR(200),
      POOLING_INTERVAL_MINS VARCHAR(10) NOT NULL,
      IN_MAILBOX VARCHAR(255),
      FILE_TYPE VARCHAR(100),
      IS_ACTIVE VARCHAR(1) DEFAULT 'Y' NOT NULL ,
      IS_HUB_INFO VARCHAR(1) DEFAULT 'N' NOT NULL,
      CREATED_BY VARCHAR(15) NOT NULL,
      LAST_UPDATED_BY VARCHAR(15),
      LAST_UPDATED_DT DATETIME2 (6), PRIMARY KEY (PK_ID)
    );


--------------------------------------------------------
--  DDL for PETPE_AWS_S3
--------------------------------------------------------

CREATE TABLE PETPE_CD
    ( PK_ID VARCHAR(20) NOT NULL,
      SUBSCRIBER_TYPE VARCHAR(5) NOT NULL,
      SUBSCRIBER_ID VARCHAR(20) NOT NULL,
      LOCAL_NODE_NAME VARCHAR(255),
      REMOTE_FILE_NAME VARCHAR(255),
      NODE_NAME VARCHAR(255),
      SNODE_ID VARCHAR(255),
      SNODE_ID_PASSWORD VARCHAR(255),
      OPERATING_SYSTEM VARCHAR(255),
      DIRECTORY VARCHAR(255),
      HOST_NAME VARCHAR(200),
      PORT VARCHAR(50),
      COPY_SIS_OPTS VARCHAR(255),
      CHECK_POINT VARCHAR(100),
      COMPRESSION_LEVEL VARCHAR(255),
      DISPOSITION VARCHAR(255),
      SUBMIT VARCHAR(200),
      SECURE VARCHAR(10) ,
      RUN_JOB VARCHAR(255),
      RUN_TASK VARCHAR(100),
      CA_CERTIFICATE_NAME VARCHAR(255),
      CIPHER_SUITS VARCHAR(max),
      DCB_PARAM VARCHAR(255),
      DNS_NAME VARCHAR(255),
      UNIT VARCHAR(255),
      STORAGE_CLASS VARCHAR(255),
      SECURITY_PROTOCOL VARCHAR(255),
      SPACE VARCHAR(255),
      ADAPTER_NAME VARCHAR(200),
      POOLING_INTERVAL_MINS VARCHAR(10),
      IS_ACTIVE VARCHAR(1) DEFAULT 'Y' NOT NULL,
      IS_HUB_INFO VARCHAR(1) DEFAULT 'N' NOT NULL,
      CREATED_BY VARCHAR(15) NOT NULL,
      LAST_UPDATED_BY VARCHAR(15),
      LAST_UPDATED_DT DATETIME2 (6), PRIMARY KEY (PK_ID)
    );

CREATE SEQUENCE SEQ_PETPE_PEM_GEN START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 NO CYCLE CACHE 10;

ALTER TABLE PETPE_SFG_FTP ADD PRF_AUTH_TYPE VARCHAR(15);

ALTER TABLE PETPE_PROCESSDOCS ALTER COLUMN PROCESS_RULESEQ VARCHAR(2000);
