--------------------------------------------------------
--  DDL for Table PETPE_CD
--------------------------------------------------------

EXEC sp_rename 'PETPE_CD', 'PETPE_SFG_CD';

CREATE TABLE PETPE_CD
   (    PK_ID VARCHAR(20) NOT NULL,
    SUBSCRIBER_TYPE VARCHAR(5) NOT NULL,
    SUBSCRIBER_ID VARCHAR(20) NOT NULL,
    REMOTE_HOST VARCHAR(255) NOT NULL,
	REMOTE_PORT VARCHAR(10) NOT NULL,
	REMOTE_USER VARCHAR(255),
	REMOTE_PASSWORD VARCHAR(50),
	TRANSFER_TYPE VARCHAR(20),
	LOCAL_NODE_NAME VARCHAR(255),
	REMOTE_NODE_NAME VARCHAR(255),
	CODE_PAGE_FROM VARCHAR(20),
    CODE_PAGE_TO VARCHAR(20),
	LOCAL_XLATE VARCHAR(255),
	DCB VARCHAR(255),
	SYS_OPTS VARCHAR(255),
	SECURITY_PROTOCOL VARCHAR(100),
	SECURE_PLUS VARCHAR(100),
	CA_CERTIFICATE VARCHAR(100),
	CIPHER_SUITS VARCHAR(555),
	ADAPTER_NAME VARCHAR(100),
	POLLING_INTERVAL VARCHAR(20),
	IS_ACTIVE VARCHAR(1) DEFAULT 'N' NOT NULL ,
    IS_HUB_INFO VARCHAR(1) DEFAULT 'N' NOT NULL ,
    CREATED_BY VARCHAR(100) NOT NULL,
    LAST_UPDATED_BY VARCHAR(100),
    LAST_UPDATED_DT DATETIME2 (6) , PRIMARY KEY (PK_ID)
   );

UPDATE PETPE_TRADINGPARTNER SET TP_PROTOCOL  = 'SFG_CONNECT_DIRECT' WHERE TP_PROTOCOL  = 'Connect:Direct';
UPDATE PETPE_APPLICATION SET APP_INTEGRATION_PROTOCOL  = 'SFG_CONNECT_DIRECT' WHERE APP_INTEGRATION_PROTOCOL  = 'Connect:Direct';

--------------------------------------------------------
--  DDL for Table PETPE_FTP
--------------------------------------------------------
ALTER TABLE PETPE_FTP ALTER COLUMN TRANSFER_TYPE VARCHAR(10) NULL;
ALTER TABLE PETPE_FTP ADD CWD_UP VARCHAR(20);
ALTER TABLE PETPE_FTP ADD QUOTE VARCHAR(255);
ALTER TABLE PETPE_FTP ADD SITE VARCHAR(255);
ALTER TABLE PETPE_FTP ADD CONNECTION_TYPE VARCHAR(15);
ALTER TABLE PETPE_FTP ADD MB_DESTINATION VARCHAR(255);
ALTER TABLE PETPE_FTP ADD MB_DESTINATION_LOOKUP VARCHAR(50);
ALTER TABLE PETPE_FTP ADD SSL_SOCKET VARCHAR(40);
ALTER TABLE PETPE_FTP ADD SSL_CIPHER VARCHAR(255);
ALTER TABLE PETPE_FTP ADD SSH_AUTHENTICATION VARCHAR(40);
ALTER TABLE PETPE_FTP ADD SSH_CIPHER VARCHAR(40);
ALTER TABLE PETPE_FTP ADD SSH_COMPRESSION VARCHAR(40);
ALTER TABLE PETPE_FTP ADD SSH_MAC VARCHAR(40);
ALTER TABLE PETPE_FTP ADD SSH_IDENTITY_KEY_ID VARCHAR(255);
