--------------------------------------------------------
--  DDL for Table PETPE_RULES
--------------------------------------------------------
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_16 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_17 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_18 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_19 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_20 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_21 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_22 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_23 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_24 VARCHAR(200);
ALTER TABLE PETPE_RULES ADD PROPERTY_NAME_25 VARCHAR(200);

--------------------------------------------------------
--  DDL for Table PETPE_PROCESSRULES
--------------------------------------------------------
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_16 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_17 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_18 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_19 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_20 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_21 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_22 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_23 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_24 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES ADD PROPERTY_NAME_25 VARCHAR(200);
