--------------------------------------------------------
--  DDL for Table PETPE_TRANSFERINFO 
-------------------------------------------------------- 
CREATE TABLE PETPE_TRANSFERINFO  
   (    SEQID BIGINT NOT NULL,
    FILEARRIVED DATETIME2 (6),
    FLOWINOUT VARCHAR(120),
    TYPEOFTRANSFER VARCHAR(100),
    SENDERID VARCHAR(100),
    RECIVERID VARCHAR(100),
    APPLICATION VARCHAR(100),
    APPINTSTATUS VARCHAR(100),
    PARTNERACKSTATUS VARCHAR(100),
    SRCPROTOCOL VARCHAR(100),
    SRCFILENAME VARCHAR(100),
    SRCARCFILELOC VARCHAR(500),
    DESTFILENAME VARCHAR(100),
    DESTARCFILELOC VARCHAR(500),
    DESTPROTOCOL VARCHAR(100),
    DOCTYPE VARCHAR(100),
    PICKBPID VARCHAR(100),
    COREBPID VARCHAR(100),
    DELIVERYBPID VARCHAR(100),
    STATUS VARCHAR(100),
    ERRORSTATUS VARCHAR(100),
    ADVERRORSTATUS VARCHAR(300),
    PARTNER VARCHAR(100),
    DOCTRANS VARCHAR(15),
    CORRELATION_VALUE_1 VARCHAR(max),
    CORRELATION_VALUE_2 VARCHAR(max),
    CORRELATION_VALUE_3 VARCHAR(max),
    CORRELATION_VALUE_4 VARCHAR(max),
    CORRELATION_VALUE_5 VARCHAR(max),
    CORRELATION_VALUE_6 VARCHAR(max),
    CORRELATION_VALUE_7 VARCHAR(max),
    CORRELATION_VALUE_8 VARCHAR(max),
    CORRELATION_VALUE_9 VARCHAR(max),
    CORRELATION_VALUE_10 VARCHAR(max) , PRIMARY KEY (SEQID)

   );

--------------------------------------------------------
--  DDL for Table PETPE_TRANSINFOD
--------------------------------------------------------
CREATE TABLE PETPE_TRANSINFOD  
   (	PK_ID VARCHAR(50) NOT NULL,    
	BPID VARCHAR(256),
    RULENAME VARCHAR(256),
    BPNAME VARCHAR(256),
    DETAILS VARCHAR(4000),
    SEQUENCE VARCHAR(20) , PRIMARY KEY (PK_ID)
   );
