--------------------------------------------------------
--  DDL for Index
--------------------------------------------------------
CREATE INDEX IND_TI_FILEARRIVED ON PETPE_TRANSFERINFO (FILEARRIVED);
CREATE INDEX IND_TI_APPLICATION ON PETPE_TRANSFERINFO (APPLICATION);
CREATE INDEX IND_TI_PARTNER ON PETPE_TRANSFERINFO (PARTNER);
CREATE INDEX IND_TI_SRCPROTOCOL ON PETPE_TRANSFERINFO (SRCPROTOCOL);
CREATE INDEX IND_TI_DOCTYPE ON PETPE_TRANSFERINFO (DOCTYPE);
CREATE INDEX IND_TI_FLOWINOUT ON PETPE_TRANSFERINFO (FLOWINOUT);

CREATE INDEX IND_APP_APPNAME ON PETPE_APPLICATION (APPLICATION_NAME) ;

CREATE INDEX IND_PD_DOCTYPE ON PETPE_PROCESSDOCS  (DOCTYPE) ;
CREATE INDEX IND_PD_DOCTRANS ON PETPE_PROCESSDOCS  (DOCTRANS) ;
CREATE INDEX IND_PD_PARTNERID ON PETPE_PROCESSDOCS  (PARTNERID) ;
CREATE INDEX IND_PD_RECIVERID ON PETPE_PROCESSDOCS  (RECIVERID) ;

CREATE INDEX IND_TP_TPNAME ON PETPE_TRADINGPARTNER  (TP_NAME) ;

CREATE INDEX IND_PR_RULE_NAME ON PETPE_PROCESSRULES (RULE_NAME) ;
CREATE INDEX IND_PR_PROPNAME1 ON PETPE_PROCESSRULES (PROPERTY_NAME_1) ;
CREATE INDEX IND_PR_PROPNAME2 ON PETPE_PROCESSRULES (PROPERTY_NAME_2) ;
CREATE INDEX IND_PR_PROPNAME3 ON PETPE_PROCESSRULES (PROPERTY_NAME_3) ;
CREATE INDEX IND_PR_PROPNAME4 ON PETPE_PROCESSRULES (PROPERTY_NAME_4) ;
CREATE INDEX IND_PR_PROPNAME5 ON PETPE_PROCESSRULES (PROPERTY_NAME_5) ;
CREATE INDEX IND_PR_PROPNAME6 ON PETPE_PROCESSRULES (PROPERTY_NAME_6) ;
CREATE INDEX IND_PR_PROPNAME7 ON PETPE_PROCESSRULES (PROPERTY_NAME_7) ;
CREATE INDEX IND_PR_PROPNAME8 ON PETPE_PROCESSRULES (PROPERTY_NAME_8) ;
CREATE INDEX IND_PR_PROPNAME9 ON PETPE_PROCESSRULES (PROPERTY_NAME_9) ;
CREATE INDEX IND_PR_PROPNAME10 ON PETPE_PROCESSRULES (PROPERTY_NAME_10) ;
CREATE INDEX IND_PR_PROPNAME11 ON PETPE_PROCESSRULES (PROPERTY_NAME_11) ;
CREATE INDEX IND_PR_PROPNAME12 ON PETPE_PROCESSRULES (PROPERTY_NAME_12) ;
CREATE INDEX IND_PR_PROPNAME13 ON PETPE_PROCESSRULES (PROPERTY_NAME_13) ;

CREATE INDEX PETPE_PRRULES_PROCESS_DOC_REF ON PETPE_PROCESSRULES (PROCESS_DOC_REF);
