/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc, Version 6.1 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.pe.pcm.enums;

/**
 * @author Chenchu Kiran.
 */
public enum DisplayFields {

    NO_FIELD_FOUND("No Field Found"),
    HOSTNAME("Host Name"),
    PORTNO("Port No"),
    USERID("User Name"),
    PASSWORD("Password"),
    INDIRECTORY("In Directory"),
    OUTDIRECTORY("Out Directory"),
    DELETEAFTERCOLLECTION("Delete After Collection"),
    TRANSFERTYPE("Transfer Type"),
    POOLINGINTERVALMINS("Pooling Interval"),
    CERTIFICATEID("Certificate Id"),
    KNOWNHOSTKEY("Known Host Key"),
    USERIDENTITYKEY("User Identity Key"),
    ISHUBINFO("Hub Info"),
    ADAPTERNAME("Adapter Name"),
    CONNECTIONTYPE("Connection Type"),
    RETRYINTERVAL("Retry Interval"),
    NOOFRETRIES("Number Of Retries"),
    ENCRYPTIONSTRENGTH("Encryption Strength"),
    USECCC("Use CCC"),
    USEIMPLICITSSL("Use Implicit SSL"),
    INMAILBOX("In Mailbox"),
    OUTMAILBOX("Out Mailbox"),
    OUTBOUNDURL("OutboundUrl"),
    CERTIFICATE("Certificate Id"),
    QUEUEMANAGER("Queue Manager"),
    QUEUENAME("Queue Name"),
    FILETYPE("File Type"),
    LOCALNODENAME("Local Node Name"),
    NODENAME("Node Name"),
    REMOTEFILENAME("Remote File Name"),
    REMOTEUSERID("Remote User name"),
    REMOTEPASSWORD("Remote Password"),
    FSAADAPTER("Adapter Name "),
    USERNAME("User Name"),
    FILTER("Filter"),
    SAPROUTE("SAP Route"),
    SAPADAPTERNAME("Adapter Name"),
    WEBSERVICENAME("Name"),
    ECPROTOCOL("Protocol"),
    ECPROTOCOLREF("Protocol Reference"),
    EXCHANGECERTIFICATE("Exchange Certificate"),
    SIGNINGCERTIFICATION("Signing Certificate"),
    KEYCERTIFICATION("Key Certificate"),
    NAME("Name"),
    ACCESSPROTOCOL("Access Protocol"),
    MAILSERVER("Mail Server"),
    MAILSERVERPORT("Mail Server Port"),
    CONNECTIONRETRIES("Connection Retries"),
    MAXMSGSSESSION("Max Messages Session"),
    REMOVEINBOXMAILMSGS("Remove Inbox Mail Messages"),
    SSL("SSL"),
    KEYCERTPASSPHRASE("Key Cert Passphrase"),
    CIPHERSTRENGTH("Cipher Strength"),
    KEYCERT("Key Cert"),
    CACERTIFICATES("Ca Certificates"),
    URINAME("Uri Name"),
    //For As2
    AS2IDENTIFIER("As2 Identifier"),
    URL("End Point"),
    SENDERID("SenderId"),
    SENDERQUALIFIER("Sender Qualifier"),
    PAYLOADSECURITY("PayLoad Security"),
    PAYLOADENCRYPTIONALGORITHM("PayLoad Encryption Algorithm"),
    ISHTTPS("isHttps"),
    SSLTYPE("Ssl Type"),
    ENCRYPTIONALGORITHM("Encryption Algorithm"),
    SIGNATUREALGORITHM("Signature Algorithm"),
    ISMDNREQUIRED("MDN Required"),
    MDNTYPE("MDN Type"),
    MDNENCRYPTION("MDN Encryption"),
    RECEIPTTOADDRESS("Receipt Address"),
    HTTPCLIENTADAPTER("Http Client Adapter"),
    PAYLOADTYPE("PayLoad Type"),
    MIMETYPE("Mime Type"),
    MIMESUBTYPE("Mime Sub-Type"),
    COMPRESSDATA("Compress Data"),
    EMAILADDRESS("Email Address"),
    EMAILHOST("Email Host"),
    EMAILPORT("Email Port"),
    RESPONSETIMEOUT("Response Timeout"),
    KEYCERTPATH("Key Cert Path"),
    EXCHGCERT("Exchange Certificate"),
    EXCHGCERTPATH("Exchange Cert Path"),
    SIGNINGCERT("Signing Certificate"),
    SIGNINGCERTPATH("Signing Cert Path"),
    CACERT("CA Certificate"),
    CACERTPATH("CA Cert Path"),
    SNODEID("SNODEID"),
    SNODEIDPASSWORD("SNODEID Password"),
    OPERATINGSYSTEM("Operating System"),
    DIRECTORY("Directory/Folder"),
    PORT("Port"),
    COPYSISOPTS("CopySisOpts"),
    CHECKPOINT("Check Point"),
    COMPRESSIONLEVEL("Compression Level"),
    DISPOSITION("Disposition"),
    SUBMIT("Submit"),
    SECURE("Secure"),
    RUNJOB("RunJob"),
    RUNTASK("RunTask"),
    CACERTIFICATENAME("CA Certificate"),
    CIPHERSUITS("Cipher Suits"),
    DCBPARAM("DCB Param"),
    DNSNAME("DNS Name"),
    UNIT("Unit"),
    STORAGECLASS("Storage Class"),
    FILENAME("File Name"),
    SOURCEPATH("Source Path"),
    BUCKETNAME("Bucket Name"),
    ACCESSKEY("Access Key"),
    SECRETKEY("Secret Key"),
    ENDPOINT("End Point"),
    REGION("Region"),
    SECURITYPROTOCOL("Security Protocol"),
    SPACE("Space"),
    PRFAUTHTYPE("Authentication Type"),
    CWDUP("Cwd Up"),
    QUOTE("Quote"),
    SITE("Site"),
    MBDESTINATION("Mb Destination"),
    MBDESTINATIONLOOKUP("Mb Destination Lookup"),
    SSLSOCKET("Ssl Socket"),
    SSLCIPHER("Ssl Cipher"),
    SSHAUTHENTICATION("Ssh Authentication"),
    SSHCIPHER("Ssh Cipher"),
    SSHCOMPRESSION("Ssh Compression"),
    SSHMAC("Ssh Mac"),
    SSHIDENTITYKEYID("Ssh Identity Key Id"),
    REMOTEHOST("Remote Host"),
    REMOTEPORT("Remote Port"),
    REMOTEPASS("Remote Pass"),
    REMOTENODENAME("Remote Node Name"),
    CODEPAGEFROM("Code Page From"),
    CODEPAGETO("Code Page To"),
    LOCALXLATE("Local X Late"),
    DCB("Dcb"),
    SYSOPTS("Sys Opts"),
    SECUREPLUS("Secure Plus"),
    CACERTIFICATE("Ca Certificate"),
    REMOTEUSER("Remote User"),
    POOLINGINTERVAL("Pooling Interval"),
    AUTHUSERKEYS("SSH Auth User Keys"),
    CACERTID("Ca Cert Id"),
    EXCHGCERTNAME("Exchange Cert Name"),
    SIGNINGCERTNAME("Signing Cert Name"),
    CACERTIFICATEID("Certificate Id"),
    CACERTNAME("Certificate Name"),
    KNOWNHOSTKEYID("Known HostKey Id"),
    SSHIDENTITYKEYNAME("SSH IdentityKey Name"),
    AUTHUSERKEYID("Auth UserKey Id"),
    USERIDENTITYKEYID("User IdentityKey Id"),
    SCIPROFILEID("Sci Profile Id"),
    CONNECTIONTYPEFLAG("Connection Type Flag"),
    INBOUNDCONNECTIONTYPE("Inbound ConnectionType"),
    OUTBOUNDCONNECTIONTYPE("Outbound ConnectionType"),
    APPENDSUFFIXTOUSERNAME("Append Suffix To Username"),
    ASCIIARMOR("Ascii Armor"),
    AUTHENTICATIONHOST("Authentication Host"),
    AUTHENTICATIONTYPE("Authentication Type"),
    AUTHORIZEDUSERKEYNAME("Authorized UserKey Name"),
    CITY("City"),
    CODE("Code"),
    COMMUNITY("Community"),
    COUNTYORREGION("Country Or Region"),
    CUSTOMPROTOCOLEXTENSIONS("Custom Protocol Extensions"),
    CUSTOMPROTOCOLNAME("Custom Protocol Name"),
    DOESREQUIRECOMPRESSEDDATA("Does Require Compressed Data"),
    DOESREQUIREENCRYPTEDDATA("Does Require Encrypted Data"),
    DOESREQUIRESIGNEDDATA("Does Require Signed Data"),
    DOESUSESSH("Does Use Ssh"),
    GIVENNAME("Given Name"),
    ISINITIATINGCONSUMER("Is Initiating Consumer"),
    ISINITIATINGPRODUCER("Is Initiating Producer"),
    ISLISTENINGCONSUMER("Is Listening Consumer"),
    ISLISTENINGPRODUCER("Is Listening Producer"),
    KEYENABLED("Key Enabled"),
    MAILBOX("Mail box"),
    PASSWORDPOLICY("Password Policy"),
    POLLINGINTERVAL("Polling Interval"),
    POSTALCODE("Postal Code"),
    PUBLICKEYID("PublicKey Id"),
    REMOTEFILEPATTERN("Remote File Pattern"),
    SESSIONTIMEOUT("Session Timeout"),
    STATEORPROVINCE("State Or Province"),
    SURNAME("Surname"),
    TEXTMODE("Text Mode"),
    TIMEZONE("Time Zone"),
    USEGLOBALMAILBOX("Use Global Mailbox"),
    MERGEUSER("Merge User"),
    CHANNELNAME("Channel Name"),
    FOLDERNAME("Folder Name"),
    ENDPOINTURL("End Point URL"),
    PROJECTID("Project Id"),
    CLIENTID("Client Id"),
    CLIENTSECRET("Client Secret"),
    CLIENTEMAIL("Client Email"),
    AUTHJSON("auth Json");




    private String displayField;

    DisplayFields(String displayField) {
        this.displayField = displayField;
    }

    public String getDisplayField() {
        return this.displayField;
    }

}
