/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

--------------------------------------------------------
--  DML STATEMENTS
--------------------------------------------------------
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('Triple DES 168 CBC with PKCS5 padding','DESEDE-168');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('56-bit DES CBC with PKCS5 padding','DES-56');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('128-bit RC2 CBC with PKCS5 padding','RC2-128');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('40-bit RC2 CBC with PKCS5 padding','RC2-40');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('true','Y');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('false','N');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('SSL_NONE','N');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('Connect:Direct','SFG_CONNECT_DIRECT');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('SSL_MUST','N');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('SFTP Pull','SFGSFTP');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('FTP Push','SFGFTP');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('FTP Pull','SFGFTP');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('FTPS Push','SFGFTPS');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('FTPS Pull','SFGFTPS');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('PGP','PGP');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('SFTP Push','SFGSFTP');
INSERT INTO PETPE_PEM_PARTNER_CODES (PARTNER_NAME,PARTNER_CODE) VALUES ('AS2','AS2');
