/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
--------------------------------------------------------
--  DDL for Table PETPE_RULES
--------------------------------------------------------
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_16 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_17 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_18 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_19 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_20 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_21 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_22 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_23 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_24 VARCHAR(200);
ALTER TABLE PETPE_RULES
    ADD COLUMN PROPERTY_NAME_25 VARCHAR(200);

--------------------------------------------------------
--  DDL for Table PETPE_PROCESSRULES
--------------------------------------------------------
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_16 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_17 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_18 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_19 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_20 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_21 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_22 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_23 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_24 VARCHAR(200);
ALTER TABLE PETPE_PROCESSRULES
    ADD COLUMN PROPERTY_NAME_25 VARCHAR(200);

