/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc.
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

--------------------------------------------------------
--  DDL STATEMENTS
--------------------------------------------------------

INSERT INTO PETPE_TRADINGPARTNER (PK_ID,TP_NAME,TP_ID,ADDRESS_LINE1,ADDRESS_LINE2,EMAIL,PHONE,TP_PROTOCOL,TP_PICKUP_FILES,FILE_TP_SERVER,PARTNER_PROTOCOL_REF,TP_IS_ACTIVE,IS_PROTOCOL_HUB_INFO,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DT,PARTNER_PRIORITY,CUSTOM_TP_NAME,PGP_INFO,IP_WHITELIST,IS_ONLY_PCM,PEM_IDENTIFIER) VALUES ('TPW4L8Yr','Template_Demo','Template_Demo',NULL,NULL,'Template_Demo@templetedemo.com','111-111-111','Mailbox','N','Y','MB6K64m','N','N','cm_user','cm_user','2020-08-20 13:28:16.796000',NULL,NULL,NULL,NULL,'N',NULL);
INSERT INTO PETPE_MAILBOX (PK_ID,SUBSCRIBER_TYPE,SUBSCRIBER_ID,PROTOCOL_TYPE,IN_MAILBOX,OUT_MAILBOX,POOLING_INTERVAL_MINS,IS_ACTIVE,IS_HUB_INFO,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DT,"FILTER",MBPARTNER_PRIORITY) VALUES ('MB6K64m','TP','TPW4L8Yr','Mailbox','/Template_Demo/In','/Template_Demo/Out','ON','Y','N','cm_user','cm_user','2020-08-20 13:28:16.790000',NULL,NULL);

INSERT INTO PETPE_APPLICATION (PK_ID,APPLICATION_NAME,APPLICATION_ID,EMAIL_ID,PHONE,APP_INTEGRATION_PROTOCOL,APP_PICKUP_FILES,APP_DROP_FILES,APP_PROTOCOL_REF,APP_IS_ACTIVE,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DT,PEM_IDENTIFIER) VALUES ('APPEOhQI','Template_Application','Template_Application','admin@TemplateApplication.com','11234567890','Mailbox','N','Y','MBGpcvN','Y','cm_user','cm_user','2020-08-20 18:42:11.229000',NULL);
INSERT INTO PETPE_MAILBOX (PK_ID,SUBSCRIBER_TYPE,SUBSCRIBER_ID,PROTOCOL_TYPE,IN_MAILBOX,OUT_MAILBOX,POOLING_INTERVAL_MINS,IS_ACTIVE,IS_HUB_INFO,CREATED_BY,LAST_UPDATED_BY,LAST_UPDATED_DT,"FILTER",MBPARTNER_PRIORITY) VALUES ('MBGpcvN','APP','APPEOhQI','Mailbox','/Template_Application/in','/Template_Application/Out','ON','Y','N','cm_user','cm_user','2020-08-20 18:42:11.233000',NULL,NULL);

INSERT INTO PETPE_PROCESS (SEQ_ID,PARTNER_PROFILE,APPLICATION_PROFILE,SEQ_TYPE,FLOW,FILE_NAME) VALUES ('PMbqZfn2e','TPW4L8Yr','APPEOhQI','MFT','Outbound',NULL);
INSERT INTO PETPE_PROCESS (SEQ_ID,PARTNER_PROFILE,APPLICATION_PROFILE,SEQ_TYPE,FLOW,FILE_NAME) VALUES ('PO69dYa2f','TPW4L8Yr','APPEOhQI','MFT','Inbound',NULL);

INSERT INTO PETPE_PROCESSDOCS (PK_ID,PROCESS_REF,DOCTYPE,PARTNERID,RECIVERID,DOCTRANS,FILENAME_PATTERN,PROCESS_RULESEQ,PROCESSRULE_REF,VERSION) VALUES ('PDPyQjLp','PMbqZfn2e',NULL,NULL,NULL,NULL,'.+','PRwO56IuCK',NULL,NULL);
INSERT INTO PETPE_PROCESSDOCS (PK_ID,PROCESS_REF,DOCTYPE,PARTNERID,RECIVERID,DOCTRANS,FILENAME_PATTERN,PROCESS_RULESEQ,PROCESSRULE_REF,VERSION) VALUES ('PDmAmYbI','PO69dYa2f',NULL,NULL,NULL,NULL,'.+','PRYCKFgmh6',NULL,NULL);

INSERT INTO PETPE_PROCESSRULES (PK_ID,RULE_ID,RULE_NAME,PROPERTY_NAME_1,PROPERTY_NAME_2,PROPERTY_NAME_3,PROPERTY_NAME_4,PROPERTY_NAME_5,PROPERTY_NAME_6,PROPERTY_NAME_7,PROPERTY_NAME_8,PROPERTY_NAME_9,PROPERTY_NAME_10,PROPERTY_NAME_11,PROPERTY_NAME_12,PROPERTY_NAME_13,PROPERTY_NAME_14,PROPERTY_NAME_15,SEQ_ID,PROCESS_DOC_REF,PROPERTY_NAME_16,PROPERTY_NAME_17,PROPERTY_NAME_18,PROPERTY_NAME_19,PROPERTY_NAME_20,PROPERTY_NAME_21,PROPERTY_NAME_22,PROPERTY_NAME_23,PROPERTY_NAME_24,PROPERTY_NAME_25) VALUES ('PRYCKFgmh6','CM117','DropProcess','Mailbox','APPEOhQI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'PDmAmYbI',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO PETPE_PROCESSRULES (PK_ID,RULE_ID,RULE_NAME,PROPERTY_NAME_1,PROPERTY_NAME_2,PROPERTY_NAME_3,PROPERTY_NAME_4,PROPERTY_NAME_5,PROPERTY_NAME_6,PROPERTY_NAME_7,PROPERTY_NAME_8,PROPERTY_NAME_9,PROPERTY_NAME_10,PROPERTY_NAME_11,PROPERTY_NAME_12,PROPERTY_NAME_13,PROPERTY_NAME_14,PROPERTY_NAME_15,SEQ_ID,PROCESS_DOC_REF,PROPERTY_NAME_16,PROPERTY_NAME_17,PROPERTY_NAME_18,PROPERTY_NAME_19,PROPERTY_NAME_20,PROPERTY_NAME_21,PROPERTY_NAME_22,PROPERTY_NAME_23,PROPERTY_NAME_24,PROPERTY_NAME_25) VALUES ('PRwO56IuCK','CM117','DropProcess','Mailbox','TPW4L8Yr',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,1,'PDPyQjLp',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_TRANSFERINFO');
CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_PEM_TEMP');
CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_CD');
CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_HTTP');
CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_FILESYSTEM');
CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_MAILBOX');
CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_AS2');
