/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc.
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

--------------------------------------------------------
--  DDL STATEMENTS
--------------------------------------------------------

ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_1 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_2 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_3 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_4 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_5 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_6 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_7 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_8 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_9 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_10 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_11 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_12 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_13 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_14 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_15 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_16 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_17 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_18 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_19 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_20 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_21 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_22 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_23 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_24 SET DATA TYPE VARCHAR(500);
ALTER TABLE PETPE_PROCESSRULES ALTER COLUMN PROPERTY_NAME_25 SET DATA TYPE VARCHAR(500);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_PROCESSRULES');
