/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

--------------------------------------------------------
--  DDL STATEMENT
--------------------------------------------------------
ALTER TABLE PETPE_TRANSFERINFO DROP COLUMN FUNCTIONAL_ACK_DATE DROP COLUMN FUNCTIONAL_ACK_TIME;

ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN ISA_CONTROL_NUMBER TO ISA_CTL;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN GS_CONTROL_NUMBER TO GS_CTL;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN ST_CONTROL_NUMBER TO ST_CTL;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN FUNCTIONAL_ACK_REQUEST TO FA_REQ;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN SEGMENT_COUNT TO SEG_CNT;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN IDOC_NUMBER TO APP_TRAN_NUM;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN SAP_FA TO APP_FA;
ALTER TABLE PETPE_TRANSFERINFO RENAME COLUMN CHAR_CNT TO SRC_CHAR_CNT;

ALTER TABLE PETPE_TRANSFERINFO
    ADD COLUMN FA_DTM TIMESTAMP(6) ADD COLUMN APP_FA_STUS VARCHAR(15)
	ADD COLUMN APP_FA_DTM VARCHAR(15)
	ADD COLUMN DST_CHAR_CNT VARCHAR(20)
	ADD COLUMN DST_PROCL_CNT VARCHAR(20)
	ADD COLUMN BU_DIVNAME VARCHAR(20)
	ADD COLUMN TP_REF_ID VARCHAR(50)
	ADD COLUMN DLE_DTM TIMESTAMP(6);

CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_TRANSFERINFO');
CREATE
INDEX FA_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (FA_DTM);
CALL SYSPROC.ADMIN_CMD('REORG TABLE PETPE_TRANSFERINFO');
CREATE
INDEX DLE_DTM_PETPE_TRANSFERINFO ON PETPE_TRANSFERINFO (DLE_DTM);
