/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

--------------------------------------------------------
--  DDL STATEMENTS
--------------------------------------------------------
ALTER TABLE PETPE_CORRELATION_NAMES
    ADD COLUMN CORRELATION_NAME_26 VARCHAR(200) ADD COLUMN CORRELATION_NAME_27 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_28 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_29 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_30 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_31 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_32 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_33 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_34 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_35 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_36 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_37 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_38 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_39 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_40 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_41 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_42 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_43 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_44 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_45 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_46 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_47 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_48 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_49 VARCHAR(200)
    ADD COLUMN CORRELATION_NAME_50 VARCHAR(200);

ALTER TABLE PETPE_TRANSFERINFO
    ADD COLUMN CORRELATION_VALUE_26 VARCHAR(255) ADD COLUMN CORRELATION_VALUE_27 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_28 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_29 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_30 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_31 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_32 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_33 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_34 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_35 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_36 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_37 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_38 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_39 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_40 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_41 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_42 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_43 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_44 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_45 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_46 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_47 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_48 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_49 VARCHAR(255)
	ADD COLUMN CORRELATION_VALUE_50 VARCHAR(255);

ALTER TABLE PETPE_TRANSFERINFO
    ADD COLUMN ISA_CONTROL_NUMBER VARCHAR(15) ADD COLUMN GS_CONTROL_NUMBER VARCHAR(15)
       ADD COLUMN ST_CONTROL_NUMBER VARCHAR(15)
       ADD COLUMN FUNCTIONAL_ACK_DATE VARCHAR(15)
       ADD COLUMN FUNCTIONAL_ACK_TIME VARCHAR(6)
       ADD COLUMN FUNCTIONAL_ACK_REQUEST VARCHAR(1)
       ADD COLUMN SEGMENT_COUNT VARCHAR(9)
       ADD COLUMN IDOC_NUMBER VARCHAR(15)
       ADD COLUMN SAP_FA VARCHAR(15)
       ADD COLUMN XREF_NAME VARCHAR(30)
       ADD COLUMN XREF_LOOKUP VARCHAR(15);

ALTER TABLE PETPE_MQ
    ADD COLUMN PORT VARCHAR(30);
