/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

--------------------------------------------------------
--  DDL for ALL Tables ----Dec-11-2019---- USER_ID, CREATED_BY, and LAST_UPDATED_BY COLUMNS length increased to 100
--------------------------------------------------------

ALTER TABLE PETPE_APP_ACTIVITY_HISTORY
    ALTER COLUMN USER_ID SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_APPLICATION
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_APPLICATION
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_APPLICATION_SFG
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_APPLICATION_SFG
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_AS2
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_AS2
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_B2B_ACTIVITY_HISTORY
    ALTER COLUMN USER_ID SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_CORRELATION_NAMES
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_CORRELATION_NAMES
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_EC
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_EC
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_FILESYSTEM
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_FILESYSTEM
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_FTP
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_FTP
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_HTTP
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_HTTP
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_MAILBOX
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_MAILBOX
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_MQ
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_MQ
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_POOLING_INTERVAL
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_POOLING_INTERVAL
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_SAP
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_SAP
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_SFG_FTP
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_SFG_FTP
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_SMTP
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_SMTP
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_TP_ACTIVITY_HISTORY
    ALTER COLUMN USER_ID SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_TRADINGPARTNER
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_TRADINGPARTNER
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_TRADINGPARTNER_SFG
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_TRADINGPARTNER_SFG
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_WEBSERVICE
    ALTER COLUMN CREATED_BY SET DATA TYPE VARCHAR(100);

ALTER TABLE PETPE_WEBSERVICE
    ALTER COLUMN LAST_UPDATED_BY SET DATA TYPE VARCHAR(100);

