/*
 * Copyright (c) 2020 Pragma Edge Inc
 *
 * Licensed under the Pragma Edge Inc
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://pragmaedge.com/licenseagreement
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

--------------------------------------------------------
--  DDL for Table PETPE_TRADINGPARTNER
--------------------------------------------------------
CREATE TABLE PETPE_TRADINGPARTNER
(
    PK_ID                VARCHAR(20)  NOT NULL,
    TP_NAME              VARCHAR(200) NOT NULL,
    TP_ID                VARCHAR(200) NOT NULL,
    ADDRESS_LINE1        VARCHAR(100),
    ADDRESS_LINE2        VARCHAR(100),
    EMAIL                VARCHAR(250) NOT NULL,
    PHONE                VARCHAR(15)  NOT NULL,
    TP_PROTOCOL          VARCHAR(20)  NOT NULL,
    TP_PICKUP_FILES      VARCHAR(1)   NOT NULL DEFAULT 'N',
    FILE_TP_SERVER       VARCHAR(1)   NOT NULL DEFAULT 'N',
    PARTNER_PROTOCOL_REF VARCHAR(20)  NOT NULL,
    TP_IS_ACTIVE         VARCHAR(1)   NOT NULL DEFAULT 'N',
    IS_PROTOCOL_HUB_INFO VARCHAR(1)   NOT NULL DEFAULT 'N',
    CREATED_BY           VARCHAR(15)  NOT NULL,
    LAST_UPDATED_BY      VARCHAR(15),
    LAST_UPDATED_DT      TIMESTAMP(6),
    PRIMARY KEY (PK_ID)
) IN PCMTBSPACE;

--------------------------------------------------------
--  DDL for Table PETPE_TP_ACTIVITY_HISTORY
--------------------------------------------------------
CREATE TABLE PETPE_TP_ACTIVITY_HISTORY
(
    PK_ID       VARCHAR(50)  NOT NULL,
    TP_REF_ID   VARCHAR(30),
    USER_NAME   VARCHAR(100) NOT NULL,
    USER_ID     VARCHAR(15)  NOT NULL,
    ACTIVITY_DT TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
    ACTIVITY    CLOB,
    PRIMARY KEY (PK_ID)
) IN PCMTBSPACE;

--------------------------------------------------------
--  DDL for Table PETPE_TRADINGPARTNER_SFG
--------------------------------------------------------
CREATE TABLE PETPE_TRADINGPARTNER_SFG
(
    PK_ID                VARCHAR(20)            NOT NULL,
    TP_NAME              VARCHAR(200)           NOT NULL,
    TP_ID                VARCHAR(200)           NOT NULL,
    ADDRESS_LINE1        VARCHAR(100),
    ADDRESS_LINE2        VARCHAR(100),
    EMAIL                VARCHAR(250)           NOT NULL,
    PHONE                VARCHAR(15)            NOT NULL,
    TP_PROTOCOL          VARCHAR(20)            NOT NULL,
    TP_PICKUP_FILES      VARCHAR(1) DEFAULT 'N' NOT NULL,
    FILE_TP_SERVER       VARCHAR(1) DEFAULT 'N' NOT NULL,
    PARTNER_PROTOCOL_REF VARCHAR(20)            NOT NULL,
    TP_IS_ACTIVE         VARCHAR(1) DEFAULT 'N' NOT NULL,
    IS_PROTOCOL_HUB_INFO VARCHAR(1) DEFAULT 'N',
    CREATED_BY           VARCHAR(15)            NOT NULL,
    LAST_UPDATED_BY      VARCHAR(15),
    LAST_UPDATED_DT      TIMESTAMP(6),
    PARTNER_PRIORITY     VARCHAR(50),
    PRIMARY KEY (PK_ID)
) IN PCMTBSPACE;

--------------------------------------------------------
--  DDL for Table PETPE_EDIPROPERTIES
--------------------------------------------------------
CREATE TABLE PETPE_EDIPROPERTIES
(
    PK_ID               VARCHAR(20) NOT NULL,
    PARTNERID           VARCHAR(20),
    PARTNERNAME         VARCHAR(50),
    DIRECTION           VARCHAR(20),
    VALIDATEINPUT       VARCHAR(3),
    VALIDATEOUTPUT      VARCHAR(3),
    ISASENDERIDQAL      VARCHAR(5),
    ISASENDERID         VARCHAR(20),
    ISARECEIVERIDQAL    VARCHAR(5),
    ISARECEIVERID       VARCHAR(20),
    ISACONTSTD          VARCHAR(10),
    ISAAUTHINFO         VARCHAR(20),
    ISAAUTHINFOQUAL     VARCHAR(20),
    ISAAUTHSECINFO      VARCHAR(20),
    ISAAUTHSECQUAL      VARCHAR(20),
    LIMITINTERSIZE      VARCHAR(3),
    GSSENDERID          VARCHAR(20),
    GSRECEIVERID        VARCHAR(20),
    FUNCATIONALIDCODE   VARCHAR(20),
    RESPAGENCYCODE      VARCHAR(10),
    GROUPVERSION        VARCHAR(20),
    STSENDERID          VARCHAR(20),
    STRECEIVERID        VARCHAR(20),
    LASTUPDATEDBY       VARCHAR(40),
    UPDATEDON           VARCHAR(100),
    INTERVERSION        VARCHAR(20),
    RETAINENV           VARCHAR(20),
    DATAEXTRACTION      VARCHAR(30),
    EXTRACTIONMAILBOX   VARCHAR(150),
    BATCHTRANSACTION    VARCHAR(20),
    COMPLCHECK          VARCHAR(20),
    COMPLCHECKMAP       VARCHAR(150),
    HIPPACOMPLIANCE     VARCHAR(20),
    HIPPAVALLEVEL       VARCHAR(20),
    BUSINESSPROCESS     VARCHAR(200),
    INVOKEBPFORISA      VARCHAR(10),
    EXPECTACK           VARCHAR(10),
    USECORRELATION      VARCHAR(20),
    ACCEPTLOOKALIAS     VARCHAR(20),
    ISAACCEPTLOOKALIAS  VARCHAR(20),
    INTACKREQ           VARCHAR(10),
    ERRORBP             VARCHAR(150),
    ACCEPTNONINTER      VARCHAR(10),
    SPOUTBOUNDENCODE    VARCHAR(20),
    TA1ALAFORM          VARCHAR(100),
    ALA999FORM          VARCHAR(20),
    GLOBALCONTNO        VARCHAR(10),
    ALAFORM997          VARCHAR(20),
    ACCNONGROUP         VARCHAR(20),
    ACKDETAILS          VARCHAR(20),
    EDIPOSTMODE         VARCHAR(100),
    USEINDICATOR        VARCHAR(5),
    ERRORBPMODE         VARCHAR(10),
    PERCONTNUMCHECK     VARCHAR(10),
    PERDUPNUMCHECK      VARCHAR(20),
    INVOKEBPMODE        VARCHAR(20),
    ACKOVERDUEHR        VARCHAR(2),
    ACKOVERDUEMIN       VARCHAR(2),
    ENCODEDOC           VARCHAR(3),
    SEGTERM             VARCHAR(25),
    SUBELETERM          VARCHAR(25),
    ELETERM             VARCHAR(25),
    RELEASECHAR         VARCHAR(25),
    GENINACK            VARCHAR(15),
    ACKDETLEVEL         VARCHAR(25),
    BPINVOKESETINPD     VARCHAR(10),
    EXTRACTIONMAILBOXBP VARCHAR(200),
    TRNSETIDCODE        VARCHAR(10),
    STREAMSEG           VARCHAR(5),
    ISAENVELOPEID       VARCHAR(200),
    ISAENVELOPENAME     VARCHAR(200),
    GSENVELOPEID        VARCHAR(200),
    GSENVELOPENAME      VARCHAR(200),
    STENVELOPEID        VARCHAR(200),
    STENVELOPENAME      VARCHAR(200),
    PRIMARY KEY (PK_ID)
) IN PCMTBSPACE;

--------------------------------------------------------
--  DDL for Table PETPE_PEM_CODE_LIST
--------------------------------------------------------
CREATE TABLE PETPE_PEM_CODE_LIST
(
    PK_ID                VARCHAR(20)  NOT NULL,
    PROFILE_NAME         VARCHAR(100) NOT NULL,
    PROTOCOL             VARCHAR(20),
    CORRELATION_VALUE_1  VARCHAR(250),
    CORRELATION_VALUE_2  VARCHAR(250),
    CORRELATION_VALUE_3  VARCHAR(250),
    CORRELATION_VALUE_4  VARCHAR(250),
    CORRELATION_VALUE_5  VARCHAR(250),
    CORRELATION_VALUE_6  VARCHAR(250),
    CORRELATION_VALUE_7  VARCHAR(250),
    CORRELATION_VALUE_8  VARCHAR(250),
    CORRELATION_VALUE_9  VARCHAR(250),
    CORRELATION_VALUE_10 VARCHAR(250),
    CORRELATION_VALUE_11 VARCHAR(250),
    CORRELATION_VALUE_12 VARCHAR(250),
    CORRELATION_VALUE_13 VARCHAR(250),
    CORRELATION_VALUE_14 VARCHAR(250),
    CORRELATION_VALUE_15 VARCHAR(250),
    CORRELATION_VALUE_16 VARCHAR(250),
    CORRELATION_VALUE_17 VARCHAR(250),
    CORRELATION_VALUE_18 VARCHAR(250),
    CORRELATION_VALUE_19 VARCHAR(250),
    CORRELATION_VALUE_20 VARCHAR(250),
    CORRELATION_VALUE_21 VARCHAR(250),
    CORRELATION_VALUE_22 VARCHAR(250),
    CORRELATION_VALUE_23 VARCHAR(250),
    CORRELATION_VALUE_24 VARCHAR(250),
    CORRELATION_VALUE_25 VARCHAR(250),
    PRIMARY KEY (PK_ID)
) IN PCMTBSPACE;

